#!/usr/bin/env bash
# publish.sh — scan the content, publish it, gate it, commit it.
#
#   ./publish.sh
#
# Any failing command stops the run before anything is committed, so a broken
# build can never become the committed tree.
set -euo pipefail
cd "$(dirname "$0")"

step() { printf '\n\033[1m· %s\033[0m\n' "$1"; }

# The first failure is the error the operator needs to see: which command, on
# which line, with which exit status. `set -e` stops the run either way.
trap 's=$?; printf "\n\033[1;31mFAIL\033[0m (exit %s): %s\n" "$s" "$BASH_COMMAND" >&2; exit "$s"' ERR

step "1/5 npm run content"
npm run content

step "2/5 python3 scripts/build_content.py"
python3 scripts/build_content.py

step "3/5 python3 scripts/build_index.py"
python3 scripts/build_index.py

step "4/5 python3 scripts/build_landing_pages.py"
python3 scripts/build_landing_pages.py
# Share cards (og:image) for new or renamed pages, then point the pages at
# them. Without Pillow the script exits 0 and pages keep og-cover.png.
if python3 scripts/build_og_images.py; then
  python3 scripts/build_landing_pages.py >/dev/null
fi

# ci.sh's step 7 is `git diff` — worktree vs index — so the build's output has
# to be staged *before* the gate, otherwise "there is a new build" and "the
# gate failed" are the same event. The four fields the builders stamp "now"
# into are put back to their committed values first: ci.sh rewrites them the
# same way, and staging fresh timestamps would leave the index ahead of the
# worktree, failing the gate on nothing but a date.
#
# Keep this table in sync with the VOLATILE table in scripts/ci.sh.
python3 - <<'PY'
import re
import subprocess
from pathlib import Path

VOLATILE = {
    "data/index.json": [(r'"generatedAt": "[^"]*"', False)],
    "data/landing-manifest.json": [(r'"generatedAt": "[^"]*"', False)],
    "SEO-LANDING-REPORT.md": [(r"Generated by `scripts/build_landing_pages\.py` on [^.]*\.", False)],
    "sitemap.xml": [(r"<lastmod>[^<]*</lastmod>", True)],
}
for path, patterns in VOLATILE.items():
    head = subprocess.run(["git", "show", f"HEAD:{path}"], capture_output=True,
                          text=True, check=True).stdout
    p = Path(path)
    work = p.read_text(encoding="utf-8")
    changed = False
    for pat, replace_all in patterns:
        m = re.search(pat, head)
        if not m:
            continue
        repl = m.group(0).replace("\\", "\\\\")
        work, n = re.subn(pat, repl, work,
                          count=0 if replace_all else 1)
        changed = changed or n > 0
    if changed:
        p.write_text(work, encoding="utf-8")
PY

git add -A

step "5/5 bash scripts/ci.sh"
bash scripts/ci.sh

git add -A

if git diff --cached --quiet; then
  echo "================================="
  echo "✅ NOTHING NEW TO PUBLISH"
  echo "================================="
  exit 0
fi

git commit -m "publish content"

echo "================================="
echo "✅ WEBSITE PUBLISHED SUCCESSFULLY"
echo "================================="
