#!/usr/bin/env python3
"""
books_engine.py | House of Aspirants - the Books Engine
================================================================================
The whole Books system, generated from two config files:

    content/books/<id>.json          the book - content only, never a link
    config/affiliate-links.json      the only place a link is ever written

    content/books/*.json ─┐
                         ├─ scripts/books_engine.py ─┬─ book-<id>.html
    config/affiliate-     │                           ├─ data/books.json        (shelf API)
    links.json ───────────┘                           └─ data/books-manifest.json (SEO registry)

NO MANUAL REGISTRATION. A file dropped into content/books/ publishes itself: the
detail page, the sitemap entry (through data/books-manifest.json, read by BOTH
index builders), the search corpus, the subject grouping, the related-content
modules and the JSON-LD all fall out of the same pass. Delete the file and the
page and the sitemap entry are pruned on the next run.

THE SHELF IS A RECOMMENDATION LIST, NOT A CATALOGUE. A card carries exactly
four things - cover, title, author and one recommendation line - under a
"View on Amazon" button. No price, no rating, no publisher, no difficulty, no
"buy it if". Grouping is by subject, derived from each book's `group`, so a
new subject appears the moment a book carries it.

WHERE IT RUNS
    scripts/build_index.py imports and calls build() just before it assembles
    sitemap.xml. That builder is the one path ci.sh, publish.sh and
    build_landing_pages.py already execute, so "drop a JSON, push, published"
    holds without a new build step or an edit to ci.sh. scripts/build-index.mjs
    (the Node twin Vercel runs) does not execute this engine - it only READS
    data/books-manifest.json - so both builders still emit byte-identical
    sitemap.xml while Python stays the single writer.

LINKS
    config/affiliate-links.json is still the only file a destination may live
    in, and content/books/*.json may still never hold one (see FORBIDDEN_KEYS
    below). The difference is where the button POINTS: a provider href is now
    the store's own URL, written straight into the anchor so the reader lands
    on Amazon in one click - no popup, no /go/ redirect stub in between.
    UTM params and the Associates tag are merged onto that URL at build time.

LAYERING
    Nothing is re-implemented here. esc/head/graph/webpage_node/breadcrumb_node
    and the link floor come from scripts/build_content.py; the related-content
    ranking comes from scripts/content_engine.py's score()/rank(). This module
    only knows what is specific to books.

USAGE
    python3 scripts/books_engine.py        # standalone, for debugging
    (normally: python3 scripts/build_index.py, which calls it)

Exit code 0 = everything published. Exit 1 = a book failed schema validation;
the build stops rather than silently unpublishing a book.
================================================================================
"""
from __future__ import annotations

import html as html_mod
import json
import os
import re
import struct
import sys
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

# `python3 scripts/books_engine.py` puts scripts/ on sys.path; so does
# `python3 scripts/build_index.py`. Run from anywhere else, fix it.
sys.path.insert(0, str(Path(__file__).resolve().parent))

import build_content as bc          # noqa: E402  (reuses head/esc/graph/chrome)
from content_engine import link_floor, score   # noqa: E402  (one ranking model)

ROOT = Path(__file__).resolve().parent.parent
DOMAIN = bc.DOMAIN
MARKER = "generated by scripts/books_engine.py - do not edit by hand"

BOOKS_DIR = ROOT / "content" / "books"
COVERS_DIR = ROOT / "assets" / "books" / "covers"
AFFILIATE_FILE = ROOT / "config" / "affiliate-links.json"
SHELF_FILE = ROOT / "data" / "books.json"
MANIFEST_FILE = ROOT / "data" / "books-manifest.json"
GO_DIR = ROOT / "go" / "book"

HUB_FILE = "books.html"
HUB_URL = f"{DOMAIN}/books"

DIFFICULTY_ORDER = ["Beginner", "Intermediate", "Advanced"]
MAX_RELATED = 4

# Optional, site-internal "read these too" seeds. Everything else in the
# related system is derived at build time from data/index.json and
# data/content-manifest.json, so a book with none of these still publishes a
# full set of related modules.
RELATED_KEYS = ("relatedBooks", "relatedQuizzes", "relatedNotes",
                "relatedCurrentAffairs")

# Book JSON may never carry a link - config/affiliate-links.json owns them all.
FORBIDDEN_KEYS = {"url", "href", "link", "affiliate", "affiliateurl",
                  "affiliate_url", "buyurl", "buy_url", "purchaseurl",
                  "purchase_url", "shopurl", "shop_url"}
FORBIDDEN_HOSTS = ("amazon.", "flipkart.", "amzn.", "bit.ly", "tinyurl")

# Collections each related module reads out of data/content-manifest.json.
NOTE_COLLECTIONS = ("notes", "subject-guides", "topic-guides", "personal-notes")
MCQ_COLLECTIONS = ("expected-mcqs", "daily-practice")
PYQ_COLLECTIONS = ("previous-year-questions",)
CA_COLLECTIONS = ("current-affairs", "magazine")


# --------------------------------------------------------------------- util --
def esc(value) -> str:
    return html_mod.escape(str(value if value is not None else ""), quote=True)


def read_json(path: Path, default=None):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return default
    except json.JSONDecodeError as exc:
        raise BuildError(f"{path.relative_to(ROOT)}: invalid JSON: {exc}")


def write_text(path: Path, text: str, encoding: str = "utf-8") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding=encoding)


class BuildError(Exception):
    """A book failed validation - the build stops, nothing is half-published."""


def humanize(value: str) -> str:
    return re.sub(r"\b([a-z])", lambda m: m.group(1).upper(),
                  re.sub(r"[-_]+", " ", str(value)).strip())


def image_size(path: Path):
    """(width, height) for the formats a cover may arrive as, else None.

    width/height on <img> is what reserves the box before the file decodes, so
    the page cannot know it without reading the header. Standard library only -
    the builder runs on a bare Python 3.12 with no imaging package installed.
    """
    try:
        blob = path.read_bytes()
    except OSError:
        return None
    if blob[:8] == b"\x89PNG\r\n\x1a\n" and blob[12:16] == b"IHDR":
        return struct.unpack(">II", blob[16:24])
    if blob[:6] in (b"GIF87a", b"GIF89a"):
        return struct.unpack("<HH", blob[6:10])
    if blob[:4] == b"RIFF" and blob[8:12] == b"WEBP":
        if blob[12:16] == b"VP8X" and len(blob) >= 30:
            return (1 + int.from_bytes(blob[24:27], "little"),
                    1 + int.from_bytes(blob[27:30], "little"))
        if blob[12:16] == b"VP8 " and len(blob) >= 30:
            # 14-bit little-endian; the top two bits are the scale factor.
            return (int.from_bytes(blob[26:28], "little") & 0x3FFF,
                    int.from_bytes(blob[28:30], "little") & 0x3FFF)
        if blob[12:16] == b"VP8L" and len(blob) >= 25 and blob[20] == 0x2F:
            b0, b1 = blob[21], blob[22]
            return ((b1 & 0x3F) << 8 | b0) + 1, \
                   ((b1 >> 6) | blob[23] << 2 | blob[24] << 10) + 1
    if blob[:2] == b"\xff\xd8":                      # JPEG: walk to a SOF marker
        i = 2
        while i + 9 < len(blob):
            if blob[i] != 0xFF:
                i += 1
                continue
            marker = blob[i + 1]
            if marker in (0xD8, 0x01) or 0xD0 <= marker <= 0xD7:
                i += 2
                continue
            length = int.from_bytes(blob[i + 2:i + 4], "big")
            if 0xC0 <= marker <= 0xCF and marker not in (0xC4, 0xC8, 0xCC):
                h, w = struct.unpack(">HH", blob[i + 5:i + 9])
                return w, h
            i += 2 + length
    return None


# ---------------------------------------------------------------- validation --
# What a book MUST carry. The shelf shows only cover, title, author, one
# recommendation line and the CTA, so a new book is a short file; everything
# the schema or the related-content ranker still wants but the reader never
# sees lives in OPTIONAL_DEFAULTS and is filled by normalize() before any of
# this module reads it. No reader guards for a missing key.
REQUIRED_STR = ("id", "slug", "title", "author", "subject",
                "recommendation", "keywords", "lastUpdated")
REQUIRED_LIST = ()
REQUIRED_TEXT = ("seoTitle", "seoDescription")

# Optional fields and the value they fall back to. `list` defaults are copied,
# so two books never share an array. Filled in normalize() after validation,
# which is why an absent field is never a validation error for these.
OPTIONAL_DEFAULTS = {
    "publisher": "",
    "difficulty": "",
    "edition": "",
    "bestFor": "",
    "buyIf": "",
    "avoidIf": "",
    "howToUse": "",
    "description": "",
    "languages": [],
    "examTags": [],
    "pros": [],
    "cons": [],
    "topicsCovered": [],
}

# A recommendation is ONE line: two lines at a phone's card width is ~110
# characters, and the shelf clamps to two lines anyway. Capping it here keeps
# an editor from quietly turning the shelf back into a review.
RECOMMENDATION_MAX = 140


def validate(book: dict, where: str, subject_ids: set, seen: set,
             known_book_ids: set, reserved: set) -> list:
    """Return a list of human-readable problems. Empty means the book publishes."""
    problems = []

    def need(key, kind=str):
        if key not in book:
            problems.append(f"missing required field `{key}`")
            return None
        if not isinstance(book[key], kind) or (
                kind is str and not str(book[key]).strip()):
            problems.append(f"`{key}` must be a non-empty "
                            f"{kind.__name__}")
            return None
        return book[key]

    for key in REQUIRED_STR:
        need(key)
    for key in REQUIRED_TEXT:
        need(key)
    for key in REQUIRED_LIST:
        if key not in book:
            problems.append(f"missing required field `{key}`")
        elif not isinstance(book[key], list) or not book[key]:
            problems.append(f"`{key}` must be a non-empty array")
        elif any(not isinstance(v, str) or not v.strip() for v in book[key]):
            problems.append(f"`{key}` may only hold non-empty strings")

    bid = str(book.get("id", ""))
    if bid and not re.fullmatch(r"[a-z0-9][a-z0-9-]*", bid):
        problems.append(f"`id` {bid!r} must be a lowercase URL slug")
    if bid and bid != where:
        problems.append(f"`id` {bid!r} must equal its file name ({where})")
    if bid in seen:
        problems.append(f"duplicate id {bid!r}")
    if bid and bid in reserved:
        problems.append(
            f"id {bid!r} collides with content/book-recommendations/{bid}.md - "
            f"both would publish {f'book-{bid}.html'}")
    if bid and bid not in known_book_ids:
        problems.append(f"no entry for {bid!r} in config/affiliate-links.json - "
                        f"the shelf would show a book with no way to get it")
    if "slug" in book and book.get("slug") != bid:
        problems.append(f"`slug` {book.get('slug')!r} must equal `id`")

    subject = str(book.get("subject", ""))
    if subject and subject_ids and subject not in subject_ids:
        problems.append(f"`subject` {subject!r} is not an id in data/subjects.json")

    if "difficulty" in book and book["difficulty"] not in DIFFICULTY_ORDER:
        problems.append(f"`difficulty` {book['difficulty']!r} must be one of "
                        f"{', '.join(DIFFICULTY_ORDER)}")

    rating = book.get("rating")
    if rating is not None:
        if not isinstance(rating, (int, float)) or not 0 <= float(rating) <= 5 \
                or round(float(rating) * 2) != float(rating) * 2:
            problems.append(f"`rating` {rating!r} must be 0-5 in half steps")

    for key, lo, hi, label in (("seoTitle", 1, 60, "must be 1-60 characters"),
                               ("seoDescription", 140, 160,
                                "must be 140-160 characters")):
        if isinstance(book.get(key), str) and book[key].strip():
            if not lo <= len(book[key]) <= hi:
                problems.append(f"`{key}` is {len(book[key])} chars, {label}")

    if "featured" in book and not isinstance(book["featured"], bool):
        problems.append("`featured` must be true or false")
    if "priority" in book and not re.fullmatch(r"0\.\d", str(book["priority"])):
        problems.append(f"`priority` {book['priority']!r} must look like \"0.7\"")
    if "lastUpdated" in book and not re.fullmatch(
            r"20\d{2}-\d{2}-\d{2}", str(book.get("lastUpdated", ""))):
        problems.append(f"`lastUpdated` {book.get('lastUpdated')!r} is not YYYY-MM-DD")

    # The shelf's whole message is this one line, so it stays one line.
    rec = str(book.get("recommendation", ""))
    if rec and len(rec) > RECOMMENDATION_MAX:
        problems.append(f"`recommendation` is {len(rec)} chars - the shelf shows "
                        f"one line of at most {RECOMMENDATION_MAX}")
    if "group" in book and len(str(book["group"])) > 40:
        problems.append("`group` must be a short subject name (max 40 chars)")

    # The affiliate-link quarantine: content may never hold a destination.
    # The related* arrays are the one exception, because they are site-internal
    # navigation (books.html, study-notes.html) - they are validated below.
    for key, value in book.items():
        if key in RELATED_KEYS:
            continue
        if key.lower() in FORBIDDEN_KEYS:
            problems.append(f"`{key}` is a link - links live in "
                            f"config/affiliate-links.json, never in book content")
            continue
        text = json.dumps(value, ensure_ascii=False).lower()
        if any(host in text for host in FORBIDDEN_HOSTS):
            problems.append(f"`{key}` contains an outbound host - links live in "
                            f"config/affiliate-links.json")
            break

    for key in RELATED_KEYS:
        value = book.get(key)
        if value is None:
            continue
        if not isinstance(value, list):
            problems.append(f"`{key}` must be an array")
            continue
        for entry in value:
            if key == "relatedBooks":
                if not isinstance(entry, str) or not entry:
                    problems.append("`relatedBooks` must hold book ids (strings)")
                elif entry not in known_book_ids:
                    problems.append(f"`relatedBooks` -> {entry!r} is not a known "
                                    f"book id")
                continue
            if not isinstance(entry, dict) or "label" not in entry \
                    or "href" not in entry:
                problems.append(f"`{key}` entries need `label` and `href`")
                continue
            href = str(entry["href"])
            if href.startswith(("http://", "https://", "//", "mailto:", "tel:", "#")):
                problems.append(f"`{key}` -> {href!r} must be a site-relative link "
                                f"like `study-notes.html`; outbound destinations "
                                f"belong in config/affiliate-links.json")

    if str(book.get("cover", "")).strip():
        cover = ROOT / str(book["cover"])
        if not cover.is_file():
            problems.append(f"`cover` {book['cover']!r} is not on disk - drop the "
                            f"image into assets/books/covers/ or set cover to \"\"")

    return problems


def normalize(book: dict) -> dict:
    """Fill every optional field once, after validation passes.

    Callers below then read book["publisher"], book["examTags"] and friends
    without guarding: a four-field JSON file publishes the same way a
    twenty-field one does. `description` falls back to `recommendation` (the
    two serve different readers - schema and ranking see the first, the shelf
    the second), and `group` falls back to the book's subject name so the
    shelf groups correctly with no group written at all.
    """
    for key, default in OPTIONAL_DEFAULTS.items():
        if key not in book:
            book[key] = list(default) if isinstance(default, list) else default
    if not str(book.get("description", "")).strip():
        book["description"] = book.get("recommendation", "")
    if not str(book.get("group", "")).strip():
        book["group"] = label_for(SUBJECT_LABELS, str(book.get("subject", "")))
    return book


# -------------------------------------------------------------- affiliates --
def load_affiliates() -> dict:
    if not AFFILIATE_FILE.exists():
        raise BuildError("config/affiliate-links.json is missing - the Books "
                         "system cannot resolve a single destination without it")
    data = read_json(AFFILIATE_FILE, {})
    providers = [p for p in (data.get("providers") or [])
                 if isinstance(p, dict) and p.get("id")]
    if not providers:
        raise BuildError("config/affiliate-links.json defines no providers")
    for p in providers:
        p.setdefault("label", humanize(p["id"]))
        p.setdefault("shortLabel", p["label"])
        p.setdefault("host", "")
        p.setdefault("external", True)
    settings = data.get("settings") or {}
    settings.setdefault("rel", "sponsored noopener nofollow")
    settings.setdefault("query", {})
    settings.setdefault("amazonAssociateTag", "")
    return {"settings": settings, "providers": providers,
            "books": {k: v for k, v in (data.get("books") or {}).items()
                      if not k.startswith("$")}}


def with_tracking(url: str, provider: dict, settings: dict) -> str:
    """Merge the tracking config into a destination. Existing keys always win."""
    if not provider.get("external", True):
        return url                                  # our own pages: no utm noise
    parts = urlsplit(url)
    query = dict(parse_qsl(parts.query, keep_blank_values=True))
    for key, value in (settings.get("query") or {}).items():
        query.setdefault(key, value)
    if provider["id"] == "amazon" and settings.get("amazonAssociateTag"):
        query["tag"] = settings["amazonAssociateTag"]
    return urlunsplit((parts.scheme, parts.netloc, parts.path,
                       urlencode(query), parts.fragment))


def providers_for(book_id: str, aff: dict) -> list:
    """Ordered, available providers only. Absent/empty == not available."""
    owned = aff["books"].get(book_id) or {}
    out = []
    for provider in aff["providers"]:
        raw = owned.get(provider["id"])
        if not isinstance(raw, str) or not raw.strip():
            continue
        target = with_tracking(raw.strip(), provider, aff["settings"])
        pid = provider["id"]
        external = bool(provider.get("external", True))
        out.append({
            "id": pid,
            "label": provider["label"],
            "shortLabel": provider["shortLabel"],
            "external": external,
            # One click: the destination IS the href, so the reader lands on
            # the shop straight from the shelf. No popup, no /go/ stub in
            # between. `with_tracking` has already merged the UTM params and
            # the Associates tag onto it, and `target` is kept beside it for
            # anything that wants the plain destination.
            "href": target,
            "target": target,
            # the rel the shelf must put on an outbound anchor, read from the
            # config so no page or script ever hardcodes a link policy.
            "rel": (str((aff.get("settings") or {}).get("rel") or "")
                    if external else ""),
        })
    return out


# ----------------------------------------------------------------- labels ---
def load_labels():
    subjects = read_json(ROOT / "data" / "subjects.json", {})
    subject_labels = {s["id"]: s.get("name") or humanize(s["id"])
                      for s in subjects.get("subjects", [])}

    exams = read_json(ROOT / "data" / "exams.json", {})
    exam_labels = {e["id"]: e.get("name") or humanize(e["id"])
                   for e in exams.get("exams", [])}
    for key, value in (exams.get("tagLabels") or {}).items():
        exam_labels.setdefault(key, value)
    return subject_labels, exam_labels


def label_for(mapping: dict, key: str) -> str:
    return mapping.get(key) or humanize(key)


# ------------------------------------------------------------ related content --
def manifest_pool():
    """Published documents from the content builder, shaped for score()."""
    cm = read_json(ROOT / "data" / "content-manifest.json", {}) or {}
    pool = []
    for item in cm.get("items", []):
        if not item.get("file"):
            continue
        pool.append({
            "file": item["file"],
            "url": item.get("url") or f"{DOMAIN}/{item['file'][:-5]}",
            "title": item.get("title") or "",
            "description": item.get("description") or "",
            "collection": item.get("collection") or "",
            "subjects": item.get("subjects") or [],
            "exams": item.get("exams") or [],
            "tags": item.get("tags") or [],
            "lang": item.get("lang") or "en",
            "published": item.get("published") or "",
        })
    return pool


def quiz_pool(index: dict, subject_id: str):
    """Live practice sets for this book's subject, same subject first."""
    out = []
    for pos, subject in enumerate(index.get("subjects", [])):
        same = subject.get("id") == subject_id
        for topic in subject.get("topics", []):
            if not topic.get("available"):
                continue
            cat = topic.get("category") or ""
            href = (f'quiz.html?subject={subject["id"]}&topic={topic["id"]}'
                    + (f"&category={cat}" if cat else ""))
            out.append({
                "href": href,
                "label": topic.get("name") or topic["id"],
                "eyebrow": subject.get("name") or subject["id"],
                "rank": (0 if same else 2) + (0.1 if (same and cat) else 0) + pos * 0.01,
            })
    out.sort(key=lambda r: r["rank"])
    return out


def related_for(book: dict, seed: dict, pool: list, quizzes: list):
    """Every related group, derived. Seeds from the book file come first and
    the automatic matches follow - with no seed at all the groups still fill,
    so no editor ever has to hand-link two books together."""
    def seed_links(key):
        return [{"href": e["href"], "label": e["label"], "eyebrow": ""}
                for e in (book.get(key) or [])]

    def ranked(collections, limit=MAX_RELATED):
        picked, seen = [], set()
        for rec, _score, _why in bc_rank(seed,
                                         [p for p in pool
                                          if p["collection"] in collections],
                                         limit=limit):
            if rec["file"] in seen:
                continue
            seen.add(rec["file"])
            picked.append({"href": rec["file"], "label": rec["title"],
                           "eyebrow": "", "sub": rec["description"]})
        return picked

    subject = book["subject"]
    subject_name = label_for(SUBJECT_LABELS, subject)

    notes = seed_links("relatedNotes") + ranked(NOTE_COLLECTIONS)
    mcqs = ranked(MCQ_COLLECTIONS)
    pyq = ranked(PYQ_COLLECTIONS)
    ca = seed_links("relatedCurrentAffairs") + ranked(CA_COLLECTIONS)
    # The curated `relatedQuizzes` seeds are Practice destinations
    # (subject.html, cluster pages), so they belong with the practice slots.
    practice = (seed_links("relatedQuizzes")
                + [{"href": "mock.html", "label": "Mock tests",
                    "eyebrow": "Practice"},
                   {"href": "quiz.html?mode=daily", "label": "Daily challenge",
                    "eyebrow": "Practice"}]
                + quizzes[:MAX_RELATED])

    # Hubs are real pages, so an empty collection still lands the reader
    # somewhere honest instead of on an empty box.
    if not notes:
        notes = [{"href": "study-notes.html", "label": "Study notes",
                  "eyebrow": "Study"},
                 {"href": "articles.html", "label": "Study guides",
                  "eyebrow": "Study"},
                 {"href": f"study.html?subject={subject}",
                  "label": f"{subject_name} in Study", "eyebrow": "Study"}]
    if not mcqs:
        mcqs = [{"href": "expected-mcqs.html", "label": "Topic-wise expected MCQs",
                 "eyebrow": "Practice"},
                {"href": "daily-practice.html", "label": "Daily practice sets",
                 "eyebrow": "Practice"}]
    if not pyq:
        pyq = [{"href": "previous-year-questions.html",
                "label": "Previous Year Questions", "eyebrow": "Papers"},
               {"href": "pyq.html", "label": "Solved papers by exam",
                "eyebrow": "Papers"}]
    if not ca:
        ca = [{"href": "current-affairs.html", "label": "Current affairs",
               "eyebrow": "Current affairs"},
              {"href": "magazine.html", "label": "Monthly magazine",
               "eyebrow": "Current affairs"}]

    self_file = f'book-{book["id"]}.html'
    books = [{"href": f'book-{rid}.html',
              "label": BOOK_INDEX.get(rid, {}).get("title", humanize(rid)),
              "eyebrow": ""}
             for rid in (book.get("relatedBooks") or []) if rid in BOOK_INDEX]
    seen_books = {e["href"] for e in books} | {self_file}
    for rec, _score, _why in bc_rank(seed,
                                     [b["seed"] for b in ALL_BOOKS
                                      if b["file"] not in seen_books],
                                     limit=MAX_RELATED):
        if rec["file"] in seen_books:
            continue
        seen_books.add(rec["file"])
        books.append({"href": rec["file"], "label": rec["title"], "eyebrow": ""})

    def cut(rows):
        out, seen = [], set()
        for row in rows:
            href = str(row["href"]).split("#", 1)[0]
            if not href or href in seen:
                continue
            seen.add(href)
            out.append(row)
            if len(out) >= MAX_RELATED:
                break
        return out

    return {"notes": cut(notes), "mcqs": cut(mcqs), "practice": cut(practice),
            "pyq": cut(pyq), "currentAffairs": cut(ca), "books": cut(books)}


def bc_rank(seed, pool, limit=MAX_RELATED):
    """content_engine.score() over a pool, sorted deterministically."""
    ranked = []
    for cand in pool:
        value, why = score(seed, cand, same_collection=False)
        if value <= 0:
            continue
        ranked.append((-value, str(cand.get("file") or cand.get("url") or ""), cand, why))
    ranked.sort(key=lambda t: (t[0], t[1]))
    return [(cand, -neg, why) for neg, _key, cand, why in ranked[:limit]]


# ------------------------------------------------------------ page fragments --
def faq_for(book: dict) -> list:
    """Questions the page actually answers, answered verbatim from the file.

    The old set leaned on buyIf / avoidIf / howToUse - the review scaffolding
    this shelf no longer shows. Every answer here comes from a field the
    reader can still see on the page, so the FAQ copy and the JSON-LD built
    from the same list can never disagree.
    """
    title = book["title"]
    out = [
        {"q": f"Who is {title} for?", "a": book["recommendation"]},
        {"q": f"What does {title} cover?", "a": book["description"]},
    ]
    exams = [label_for(EXAM_LABELS, e) for e in book["examTags"]]
    if exams:
        out.append({"q": f"Which exams is {title} useful for?",
                    "a": ", ".join(exams) + "."})
    return out


def provider_buttons(book: dict, providers: list) -> str:
    """ONE CTA, and it is the page's reason to exist.

    Label and destination both come from config/affiliate-links.json, so no
    page and no script owns either: changing "View on Amazon" to something
    else is a config edit. The button points straight at the store and opens
    in a new tab - no popup, no intermediate page. The old "Free <subject>
    sets" shortcut is gone: it was a second CTA competing with this one.
    """
    out = []
    for p in providers:
        rel = (f' rel="{esc(BOOK["settings"]["rel"])}"' if p["external"]
               else ' rel="noopener"')
        attrs = (f' data-affiliate data-book="{esc(book["id"])}" '
                 f'data-provider="{esc(p["id"])}"') if p["external"] else ""
        cls = "btn btn-primary" if p["external"] else "btn btn-soft"
        tab = ' target="_blank"' if p["external"] else ""
        out.append(f'<a class="{cls}" href="{esc(p["href"])}"{attrs}{rel}{tab}>'
                   f'{esc(p["label"])}</a>')
    if not out:
        out.append('<span class="btn btn-soft" aria-disabled="true">'
                   'Currently unavailable</span>')
    return "".join(out)


def section_head(eyebrow: str, title: str, blurb: str) -> str:
    return (f'<div class="section-head reveal"><div>'
            f'<span class="eyebrow">{esc(eyebrow)}</span>'
            f'<h2>{esc(title)}</h2><p>{esc(blurb)}</p></div></div>')


def rec_group(title: str, rows: list, cta: str = "Open →") -> str:
    if not rows:
        return ""
    cards = []
    for row in rows:
        href = str(row["href"])
        eyebrow = row.get("eyebrow") or ""
        head = (f'<span class="eyebrow">{esc(eyebrow)}</span>' if eyebrow else "")
        sub = (f'<p class="muted">{esc(row["sub"])}</p>' if row.get("sub") else "")
        cards.append(f'<a class="card card-pad reveal" href="{esc(href)}">{head}'
                     f'<h3>{esc(row["label"])}</h3>{sub}'
                     f'<p class="ilink">{esc(row.get("cta") or cta)}</p></a>')
    return (f'<div class="rec-group"><h3 class="rec-title">{esc(title)}</h3>'
            f'<div class="grid grid-3">{"".join(cards)}</div></div>')


def keep_going(book: dict) -> str:
    subject = book["subject"]
    cards = [
        ("study.html?subject=" + subject, "Study",
         f"{label_for(SUBJECT_LABELS, subject)} notes and guides"),
        ("subject.html?subject=" + subject, "Practice",
         f"{label_for(SUBJECT_LABELS, subject)} questions to attempt"),
        ("books.html", "Books", "Back to the whole shelf"),
        ("expected-mcqs.html", "Practice", "Topic-wise expected MCQs"),
        ("mock.html", "Practice", "A full-length timed paper"),
        ("previous-year-questions.html", "Papers", "Solved papers by exam"),
    ]
    body = "".join(
        f'<a class="card card-pad reveal" href="{esc(href)}">'
        f'<span class="eyebrow">{esc(eyebrow)}</span><h3>{esc(title)}</h3>'
        f'<p class="ilink">Open →</p></a>'
        for href, eyebrow, title in cards)
    head = section_head("Keep going", "Where to go next",
                        "The free material this book is meant to work beside, "
                        "not instead of.")
    return (f'<section class="section" style="padding-top:0"><div class="container">'
            f'{head}'
            f'<div class="grid grid-3">{body}</div></div></section>')


def book_page(book: dict, providers: list, related: dict, nodes: list) -> str:
    bid, title = book["id"], book["title"]
    file = f"book-{bid}.html"
    url = f"{DOMAIN}/book-{bid}"
    faq = faq_for(book)

    cover = ""
    if book.get("cover"):
        size = image_size(ROOT / book["cover"]) or (600, 900)
        cover = (f'<img class="doc-cover" src="{esc(book["cover"])}" '
                 f'alt="{esc(title)} cover" width="{size[0]}" height="{size[1]}" '
                 f'loading="lazy" decoding="async" '
                 f'style="aspect-ratio:{size[0]} / {size[1]}">')
    else:
        cover = ('<div class="book-cover book-cover-lg" aria-hidden="true">'
                 f'<span>{esc(title[:2])}</span></div>')

    # Everything this page used to carry besides the cover - badges, the
    # specifications table, "Buy it if", "Skip it if", pros and cons - is
    # gone. A book page here recommends; it does not review.
    faq_html = "".join(
        f'<div class="faq-item"><h3>{esc(item["q"])}</h3><p>{esc(item["a"])}</p></div>'
        for item in faq)

    body = f"""  <main id="main">
    <section class="page-hero">
      <div class="container">
        <nav class="breadcrumb" aria-label="Breadcrumb">
          <a href="index.html">Home</a><span>/</span><a href="books.html">Books</a><span>/</span><span>{esc(title)}</span>
        </nav>
        <span class="eyebrow">{esc(book["group"])}</span>
        <h1>{esc(title)}</h1>
        {f'<p class="muted">{esc(book["subtitle"])}</p>' if book.get("subtitle") else ''}
        <div class="book-pick">
{cover}
          <div class="book-pick-body">
            <p class="book-pick-author">{esc(book["author"])}</p>
            <div class="answer-box">
              <span class="ab-label">Why this one</span>
              <p>{esc(book["recommendation"])}</p>
            </div>
            <div class="doc-actions">{provider_buttons(book, providers)}</div>
          </div>
        </div>
      </div>
    </section>

    <section class="section" style="padding-top:0">
      <div class="container" style="max-width:860px">
        {section_head("Book questions", "What this book is for",
                      "Answered from the same facts the shelf shows, nothing more.")}
        <div class="faq-list">{faq_html}</div>
      </div>
    </section>

    <section class="section" style="padding-top:0">
      <div class="container">
        {section_head("Recommended", "Learn it, then prove it",
                      "The free material this book is meant to work beside, "
                      "not instead of.")}
        {rec_group("Related notes", related["notes"], "Read →")}
        {rec_group("Related MCQs", related["mcqs"], "Attempt →")}
        {rec_group("Practice tests", related["practice"], "Start →")}
        {rec_group("Previous year questions", related["pyq"], "Open →")}
        {rec_group("Current affairs", related["currentAffairs"], "Read →")}
        {rec_group("Related books", related["books"], "Open →")}
      </div>
    </section>
{keep_going(book)}
  </main>
"""
    body = bc.enforce_link_floor(body, "book-recommendations", file)
    html = bc.head(book["seoTitle"], book["seoDescription"], book["keywords"], url,
                   "product", bc.graph(nodes))
    return html + body + bc.TAIL


# --------------------------------------------------------------- JSON-LD -----
def book_nodes(book: dict, url: str) -> list:
    crumbs = [("Home", f"{DOMAIN}/"), ("Books", HUB_URL), (book["title"], url)]
    nodes = [
        bc.webpage_node(url, book["title"], book["seoDescription"],
                        f"{url}#breadcrumb"),
        bc.breadcrumb_node({"id": f"{url}#breadcrumb",
                            "items": [(n, u) for n, u in crumbs]}),
    ]

    book_node = {
        "@type": "Book",
        "@id": f"{url}#book",
        "name": book["title"],
        "url": url,
        "description": book["description"],
        "author": {"@type": "Person", "name": book["author"]},
        "genre": label_for(SUBJECT_LABELS, book["subject"]),
    }
    # Optional schema fields, added only when the file actually carries them.
    # A short book JSON omits publisher, edition and topic list entirely -
    # emitting them as empty nodes would be markup rich results drop, not
    # markup rich results reward.
    if book["languages"]:
        book_node["inLanguage"] = [str(lang) for lang in book["languages"]]
    if book["publisher"]:
        book_node["publisher"] = {"@type": "Organization",
                                  "name": book["publisher"]}
    if book["edition"]:
        book_node["bookEdition"] = book["edition"]
    if book["topicsCovered"]:
        book_node["about"] = [{"@type": "Thing", "name": t}
                              for t in book["topicsCovered"]]
    if book.get("cover"):
        size = image_size(ROOT / book["cover"]) or (600, 900)
        book_node["image"] = {"@type": "ImageObject",
                              "url": f'{DOMAIN}/{book["cover"]}',
                              "width": size[0], "height": size[1]}
    # No `offers` node: this site holds no price. Price comparison and live
    # offers are a documented future feature - emitting an Offer without a
    # price would be markup Google rejects, not markup Google rewards.
    nodes.append(book_node)
    nodes[0]["mainEntity"] = {"@id": f"{url}#book"}

    faq = faq_for(book)
    nodes.append({
        "@type": "FAQPage",
        "@id": f"{url}#faq",
        "mainEntity": [{
            "@type": "Question",
            "name": item["q"],
            "acceptedAnswer": {"@type": "Answer", "text": item["a"]},
        } for item in faq],
    })
    return nodes


# ----------------------------------------------------------------- redirects --
# There are none any more. A provider href is the store's own URL (see
# providers_for), so a reader reaches Amazon in one click with no /go/ stub in
# between; the prune pass in build() removes stubs older builds published.


# --------------------------------------------------------------------- build --
BOOK = {}          # resolved affiliate config, shared by the render helpers
SUBJECT_LABELS = {}
EXAM_LABELS = {}
ALL_BOOKS = []
BOOK_INDEX = {}    # book id -> {file, title}, for the relatedBooks seeds


def load_books(subject_ids: set, reserved: set, affiliate_ids: set) -> list:
    if not BOOKS_DIR.is_dir():
        return []
    loaded, errors = [], []
    for path in sorted(BOOKS_DIR.glob("*.json")):
        if path.name.startswith("$"):
            continue
        stem = path.stem
        try:
            book = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"content/books/{path.name}: invalid JSON: {exc}")
            continue
        if not isinstance(book, dict):
            errors.append(f"content/books/{path.name}: must hold one JSON object")
            continue
        for problem in validate(book, stem, subject_ids, {b["id"] for b in loaded},
                                affiliate_ids, reserved):
            errors.append(f"content/books/{path.name}: {problem}")
        loaded.append(book)
    if errors:
        raise BuildError("\n".join(f"  \u2716 {e}" for e in errors))
    loaded.sort(key=lambda b: (-bool(b.get("featured")), str(b.get("title")).lower()))
    return loaded


# The shelf has ONE dimension: the subject a book belongs to. `group` is the
# display name each book carries ("Polity", "Punjab GK", ...) and the rows are
# always derived from the books that exist (see facets()), so a new subject
# appears the moment a book does - no chip list to maintain, nothing hardcoded
# in a page or in a script.
FACET_SPEC = (
    ("group", "Subject", "group", "is"),
)


def facets(books: list) -> dict:
    """The subject groups, derived from the books that exist.

    Exactly the shape every former facet had - a label, how a chip applies to
    a record, and the rows that actually exist - which is what
    scripts/seo_check.py validates and what the shelf renders. There is simply
    only one of them now: exam, publisher, author, language, difficulty, the
    featured flag and the rating buckets were all filters this page dropped.
    """
    counts = {}
    for book in books:
        value = str(book.get("group") or "")
        if value:
            counts[value] = counts.get(value, 0) + 1
    rows = [{"id": v, "label": v, "count": c} for v, c in counts.items()]
    rows.sort(key=lambda r: (-r["count"], r["label"].lower()))
    return {key: {"key": key, "label": label, "field": field, "match": match,
                  "rows": rows}
            for key, label, field, match in FACET_SPEC}


def haystack(book: dict) -> str:
    """One pre-lowercased string per book: the whole surface the shelf search
    matches against. Built here so the browser never has to know which fields
    matter - adding a searchable field is an engine change, not a JS change."""
    parts = [book.get("id", ""), book.get("title", ""), book.get("subtitle", ""),
             book.get("author", ""), book.get("group", ""),
             book.get("recommendation", ""),
             book.get("publisher", ""), book.get("edition", ""),
             book.get("difficulty", ""), book.get("description", ""),
             book.get("keywords", ""), book.get("bestFor", ""),
             book.get("subject", ""), label_for(SUBJECT_LABELS, book["subject"])]
    parts += book.get("topicsCovered", []) + book.get("languages", [])
    parts += [label_for(EXAM_LABELS, e) for e in book.get("examTags", [])]
    return re.sub(r"\s+", " ", " ".join(str(p) for p in parts if p)).strip().lower()


def shelf_record(book: dict, providers: list) -> dict:
    size = image_size(ROOT / book["cover"]) if book.get("cover") else None
    return {
        "id": book["id"],
        "slug": book.get("slug", book["id"]),
        "title": book["title"],
        "subtitle": book.get("subtitle", ""),
        "author": book["author"],
        # The shelf card's two new fields: the subject it files itself under
        # and the one line the card prints under the author.
        "group": book["group"],
        "recommendation": book["recommendation"],
        "publisher": book["publisher"],
        "cover": book.get("cover", ""),
        "coverW": size[0] if size else 0,
        "coverH": size[1] if size else 0,
        "subject": book["subject"],
        "subjectLabel": label_for(SUBJECT_LABELS, book["subject"]),
        "difficulty": book["difficulty"],
        "rating": book.get("rating"),
        "edition": book["edition"],
        "languages": book["languages"],
        "examTags": book["examTags"],
        "examLabels": [label_for(EXAM_LABELS, e) for e in book["examTags"]],
        "description": book["description"],
        "bestFor": book["bestFor"],
        "buyIf": book["buyIf"],
        "avoidIf": book["avoidIf"],
        "howToUse": book["howToUse"],
        "featured": bool(book.get("featured")),
        "file": f'book-{book["id"]}.html',
        "url": f'{DOMAIN}/book-{book["id"]}',
        "lastUpdated": book["lastUpdated"],
        "providers": [{k: p[k] for k in
                       ("id", "label", "shortLabel", "external", "href", "rel")}
                      for p in providers],
        "search": haystack(book),
    }


def build() -> dict:
    """Publish everything. Called by scripts/build_index.py."""
    global BOOK, SUBJECT_LABELS, EXAM_LABELS, ALL_BOOKS, BOOK_INDEX

    BOOK = load_affiliates()
    SUBJECT_LABELS, EXAM_LABELS = load_labels()
    subject_ids = set(SUBJECT_LABELS)

    affiliate_ids = set(BOOK["books"])
    reserved = {p.stem for p in (ROOT / "content" / "book-recommendations").glob("*.md")
                if p.name != "README.md"} if (
                    ROOT / "content" / "book-recommendations").is_dir() else set()

    # Optional fields are filled before anything downstream reads them, so a
    # short JSON file (id, title, author, group, recommendation, cover) builds
    # the same page a full one does.
    books = [normalize(b) for b in load_books(subject_ids, reserved, affiliate_ids)]
    index = read_json(ROOT / "data" / "index.json", {}) or {}
    pool = manifest_pool()

    BOOK_INDEX = {b["id"]: {"file": f'book-{b["id"]}.html', "title": b["title"]}
                  for b in books}
    ALL_BOOKS = []
    for book in books:
        ALL_BOOKS.append({
            "id": book["id"],
            "file": f'book-{book["id"]}.html',
            "title": book["title"],
            # No `difficulty` on the seed: content_engine.score()'s
            # difficulty/category branch adds a *string* to the running total
            # (a latent defect in shared ranking code), so two records with the
            # same difficulty would raise. Facet overlap on subject, exam and
            # topics is what relates two books anyway.
            "seed": {
                "file": f'book-{book["id"]}.html',
                "collection": "books",
                "title": book["title"],
                "description": book["description"],
                "subjects": [book["subject"]],
                "exams": book["examTags"],
                "tags": book["topicsCovered"],
                "featured": bool(book.get("featured")),
            },
        })

    produced = set()
    shelf, items, pages, redirects = [], [], [], []
    cover_count = 0

    for book in books:
        bid = book["id"]
        file = f"book-{bid}.html"
        url = f"{DOMAIN}/book-{bid}"
        providers = providers_for(bid, BOOK)

        seed = next(b["seed"] for b in ALL_BOOKS if b["id"] == bid)
        related = related_for(book, seed, pool, quiz_pool(index, book["subject"]))

        write_text(ROOT / file, book_page(book, providers, related,
                                          book_nodes(book, url)))
        produced.add(file)

        # No redirect stub is written: every provider href already IS the
        # destination (see providers_for), so there is nothing to hop through.
        # `redirects` stays in the manifest as an empty list for shape
        # compatibility, and the prune pass below deletes any /go/ stub an
        # earlier build left behind.

        if book.get("cover"):
            cover_count += 1
        shelf.append(shelf_record(book, providers))
        items.append({
            "id": bid, "file": file, "url": url,
            "title": book["seoTitle"], "description": book["seoDescription"],
            "name": book["title"], "author": book["author"],
            "publisher": book["publisher"], "subject": book["subject"],
            "exams": book["examTags"], "languages": book["languages"],
            "difficulty": book["difficulty"], "rating": book.get("rating"),
            "featured": bool(book.get("featured")), "cover": book.get("cover", ""),
            "topics": book["topicsCovered"], "keywords": book["keywords"],
            "lastUpdated": book["lastUpdated"],
        })
        pages.append({"file": file, "url": url, "title": book["seoTitle"],
                      "description": book["seoDescription"],
                      "priority": str(book.get("priority", "0.7"))})

    # --- prune: a deleted book must not leave a page or a redirect behind ----
    previous = read_json(MANIFEST_FILE, {}) or {}
    for record in list(previous.get("pages", [])) + list(previous.get("redirects", [])):
        stale = str(record.get("file", ""))
        if stale and stale not in produced and stale != HUB_FILE:
            path = ROOT / stale
            if path.is_file() and MARKER in path.read_text(encoding="utf-8", errors="replace"):
                path.unlink()
    if previous.get("redirects"):
        gone = GO_DIR
        for directory in sorted((p for p in gone.rglob("*") if p.is_dir()),
                                key=lambda p: len(p.parts), reverse=True):
            try:
                directory.rmdir()
            except OSError:
                pass

    filters = facets(books)
    write_text(SHELF_FILE, json.dumps({
        "$note": ("GENERATED by scripts/books_engine.py - do not edit. Source of "
                  "truth: content/books/*.json (book content) and "
                  "config/affiliate-links.json (links). `books` is what the shelf "
                  "renders (including `search`, the pre-lowercased string the "
                  "shelf search matches on), `filters` describes every filter "
                  "dimension derived from those books (label + how a chip "
                  "matches a record + the rows that exist) and `count` is the "
                  "shelf size. Add a book by dropping a JSON file into "
                  "content/books/ and rebuilding - never edit this file."),
        "count": len(shelf),
        "filters": filters,
        "books": shelf,
    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    write_text(MANIFEST_FILE, json.dumps({
        "$note": ("GENERATED by scripts/books_engine.py - do not edit. The SEO "
                  "registry for the Books system: `pages` is read by BOTH index "
                  "builders to put every book in sitemap.xml, `hubs`/`items` are "
                  "read by scripts/seo_check.py to gate title, description, "
                  "canonical, schema and sitemap parity. `redirects` lists the "
                  "affiliate hops the engine owns so it can prune them. "
                  "No timestamps: a rebuild is byte-identical or CI fails."),
        "version": 1,
        "domain": DOMAIN,
        "generatedBy": "scripts/books_engine.py",
        "hubs": [{
            "collection": "books", "file": HUB_FILE, "url": HUB_URL,
            "title": "Recommended Books for Punjab Exams | House of Aspirants",
            "description": ("Compare preparation books for Punjab Police, PSSSB, "
                            "PPSC, SSC, banking and railway exams - what each one "
                            "covers, who it suits and who should skip it."),
            "count": len(shelf),
        }],
        "pages": pages,
        "items": items,
        "redirects": redirects,
        "counts": {"books": len(shelf), "covers": cover_count,
                   "providers": len(BOOK["providers"])},
    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    for page in pages:
        found = main_links((ROOT / page["file"]).read_text(encoding="utf-8"))
        if len(found) < 5:
            raise BuildError(f'{page["file"]}: only {len(found)} contextual links '
                             f'inside <main> - the link floor is 5')

    print(f"  \u2714 books: {len(shelf)} published, {len(redirects)} redirect(s), "
          f"{cover_count}/{len(shelf)} cover(s), "
          f"{sum(1 for f in filters.values() if f)} facet(s)")
    return {"books": len(shelf), "pages": len(pages), "redirects": len(redirects)}


def main_links(html_text: str) -> set:
    """Exactly what scripts/seo_check.py counts against the link floor."""
    match = re.search(r"<main[^>]*>(.*?)</main>", html_text, re.S)
    return link_floor(match.group(1)) if match else set()


if __name__ == "__main__":
    try:
        build()
    except BuildError as exc:
        print("\n\u2716 Books build FAILED", file=sys.stderr)
        print(str(exc), file=sys.stderr)
        sys.exit(1)
