#!/usr/bin/env python3
"""
build_content.py | House of Aspirants
===============================================================================
Markdown content system for the learning platform. No CMS, no third-party
packages: the site stays vanilla, and this builder runs on a bare Python 3.9.

WHAT IT DOES
    content/<collection>/<slug>.md   --source of truth (Git-reviewed Markdown)
                |
                v
    scripts/build_content.py
                |
                +--> <prefix>-<slug>.html     one static page per document
                +--> <hub>.html               one hub per collection
                +--> data/content-manifest.json
                |      - feeds sitemap.xml (via BOTH index builders)
                |      - feeds seo_check's content gate
                |      - feeds the homepage feed blocks (index.html)
                +--> homepage feed blocks patched between markers

COLLECTIONS (folder  ->  page prefix  ->  hub)
    content/notes/        note-       study-notes.html
    content/magazine/     magazine-   magazine.html
    content/strategy/     strategy-   strategy.html
    content/sessions/     session-    live-sessions.html
    content/recruitment/  recruit-    recruitment.html
    content/pdfs/         (registry only - the PDF is the artifact)  pdfs.html

PUNJABI VARIANTS
    A sibling `<slug>.pa.md` publishes `note-<slug>.pa.html` (lang="pa"),
    cross-linked from the English page and vice versa. Punjabi-first means the
    note itself can ship in Punjabi; English stays one tap away.

DETERMINISM
    The output never contains a run timestamp: rebuilding without editing
    content emits byte-identical files, so `scripts/ci.sh` step 5 can prove the
    committed tree is exactly what this builder produces.

USAGE
    python3 scripts/build_content.py            # build everything
    python3 scripts/build_content.py --strict   # warnings become errors
===============================================================================
"""
import html as html_mod
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOMAIN = "https://houseofaspirants.in"
CONTENT = ROOT / "content"
MANIFEST = ROOT / "data" / "content-manifest.json"
OG_IMAGE = "assets/img/og-cover.png"
OG_ABS = f"{DOMAIN}/{OG_IMAGE}"
BYLINE = "House of Aspirants Editorial Team"
BRAND_SUFFIX = " | House of Aspirants"

# Generated page prefixes - used for idempotent cleanup of stale output.
GEN_PREFIXES = ("note-", "magazine-", "strategy-", "session-", "recruit-")
GENERATED_MARKER = "generated by scripts/build_content.py - do not edit by hand"

# Official-source policy (decision: recruitment pages may only point at the
# recruiting body's own website). Anything else fails the build, so a stray
# affiliate or third-party jobs portal can never ship.
OFFICIAL_HOST_SUFFIXES = (".gov.in", ".nic.in", ".gov.uk")
OFFICIAL_HOSTS = {"pspcl.co.in", "pspcl.gov.in"}

errors, warnings, notes = [], [], []
RECRUITMENT = []            # recruitment records, filled during the load pass


def err(msg):
    errors.append(msg)


def warn(msg):
    warnings.append(msg)


def info(msg):
    notes.append(msg)


def esc(s):
    return html_mod.escape(str(s), quote=True)


# =============================================================================
# 1. FRONT MATTER  (minimal YAML subset - scalars, inline lists, block lists,
#                   one level of nested mappings, "|"" literal blocks)
# =============================================================================
LIST_FIELDS = {
    "subjects", "exams", "tags", "highlights", "dates", "syllabus", "selection",
    "expected_questions", "previous_papers", "questions", "doubts", "categories",
}


def _split_inline_list(inner):
    """Split `a, b, "c, d"` on commas that are not inside quotes."""
    items, buf, quote = [], "", ""
    for ch in inner:
        if quote:
            buf += ch
            if ch == quote:
                quote = ""
        elif ch in "\"'":
            quote = ch
            buf += ch
        elif ch == ",":
            items.append(buf.strip())
            buf = ""
        else:
            buf += ch
    if buf.strip():
        items.append(buf.strip())
    return [x for x in (_scalar(i) for i in items) if x not in ("", None)]


def _scalar(raw):
    v = raw.strip()
    # inline list:  key: [a, b, c]
    if len(v) >= 2 and v[0] == "[" and v[-1] == "]":
        return _split_inline_list(v[1:-1])
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        return v[1:-1]
    low = v.lower()
    if low in ("true", "yes"):
        return True
    if low in ("false", "no"):
        return False
    if re.fullmatch(r"-?\d+", v):
        return int(v)
    return v


def parse_front_matter(text, where):
    """-> (meta dict, body str). Raises ValueError with a line-accurate message."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{where}: file must start with a '---' front matter fence")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        raise ValueError(f"{where}: front matter fence is never closed")

    meta, i, n = {}, 1, end
    while i < n:
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        m = re.match(r"^([A-Za-z0-9_]+):\s*(.*)$", line)
        if not m:
            raise ValueError(f"{where}:{i + 1}: expected 'key: value', got {line!r}")
        key, rest = m.group(1), m.group(2)
        i += 1

        # literal block:  key: |   (indented lines follow)
        if rest in ("|", ">"):
            block = []
            while i < n and (not lines[i].strip() or lines[i][:1] in (" ", "\t")):
                block.append(lines[i].strip())
                i += 1
            meta[key] = " ".join(x for x in block if x).strip()
            continue

        # block list / nested mapping
        if rest == "":
            items, first_indent = [], None
            while i < n and lines[i].strip() and not lines[i].lstrip().startswith("#") \
                    and re.match(r"^\s+-\s", lines[i]):
                if first_indent is None:
                    first_indent = len(lines[i]) - len(lines[i].lstrip())
                item_line = lines[i]
                i += 1
                im = re.match(r"^\s+-\s+(.*)$", item_line)
                payload = im.group(1)
                # nested mapping inside a list item: "- k: v" then deeper "k: v"
                if re.match(r"^[A-Za-z0-9_]+:\s*\S", payload):
                    entry = {}
                    km = re.match(r"^([A-Za-z0-9_]+):\s*(.*)$", payload)
                    entry[km.group(1)] = _scalar(km.group(2))
                    while i < n:
                        nxt = lines[i]
                        ind = len(nxt) - len(nxt.lstrip())
                        if not nxt.strip() or ind <= first_indent:
                            break
                        if not re.match(r"^[A-Za-z0-9_]+:\s*\S", nxt.strip()):
                            break
                        km2 = re.match(r"^\s*([A-Za-z0-9_]+):\s*(.*)$", nxt)
                        entry[km2.group(1)] = _scalar(km2.group(2))
                        i += 1
                    items.append(entry)
                else:
                    items.append(_scalar(payload))
            meta[key] = items
            continue

        meta[key] = _scalar(rest)

    body = "\n".join(lines[end + 1:]).strip("\n")
    return meta, body


# =============================================================================
# 2. MARKDOWN  (headings, paragraphs, lists, tables, quotes, code, links)
#    Raw HTML in the source is escaped, never passed through: the Markdown
#    author cannot break the page or inject markup.
# =============================================================================
_INLINE_CODE = re.compile(r"`([^`]+)`")
_INLINE_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_INLINE_ITALIC = re.compile(r"(?<!\*)\*([^*\n]+)\*(?!\*)")
_LINK = re.compile(r"\[([^\]]+)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")


def md_inline(text):
    s = esc(text)
    s = _INLINE_CODE.sub(lambda m: f"<code>{m.group(1)}</code>", s)
    s = _LINK.sub(
        lambda m: f'<a href="{esc(m.group(2))}">{m.group(1)}</a>', s)
    s = _INLINE_BOLD.sub(lambda m: f"<strong>{m.group(1)}</strong>", s)
    s = _INLINE_ITALIC.sub(lambda m: f"<em>{m.group(1)}</em>", s)
    return s


def slugify(text):
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "section"


def md_to_html(src):
    """-> (html, toc) where toc = [(anchor, text), ...] for every ## heading.

    Heading levels are remapped so the page keeps one <h1> (the title) and a
    skip-free outline: Markdown '#' and '##' become h2, deeper levels follow,
    and no level ever jumps more than one.
    """
    lines = src.replace("\r\n", "\n").split("\n")
    out, toc, i, n = [], [], 0, len(lines)
    seen, last_level = {}, 0

    def anchor_for(text):
        base = slugify(text)
        seen[base] = seen.get(base, 0) + 1
        return base if seen[base] == 1 else f"{base}-{seen[base]}"

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # fenced code
        if stripped.startswith("```"):
            lang = stripped[3:].strip()
            buf = []
            i += 1
            while i < n and not lines[i].strip().startswith("```"):
                buf.append(lines[i])
                i += 1
            i += 1
            cls = f' class="language-{esc(lang)}"' if lang else ""
            out.append(f"<pre><code{cls}>{esc(chr(10).join(buf))}</code></pre>")
            continue

        # horizontal rule
        if re.fullmatch(r"(-{3,}|\*{3,}|_{3,})", stripped):
            out.append("<hr>")
            i += 1
            continue

        # heading
        m = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if m:
            raw_level = len(m.group(1))
            level = max(2, min(6, raw_level + (1 if raw_level == 1 else 0)))
            if last_level and level > last_level + 1:
                level = last_level + 1
            text = m.group(2).strip().rstrip("#").strip()
            anchor = anchor_for(text)
            if level == 2:
                toc.append((anchor, text))
            out.append(f'<h{level} id="{anchor}">{md_inline(text)}</h{level}>')
            last_level = level
            i += 1
            continue

        # table
        if stripped.startswith("|") and i + 1 < n and \
                re.match(r"^\|[\s:|-]+\|$", lines[i + 1].strip()):
            head = [c.strip() for c in stripped.strip("|").split("|")]
            i += 2
            rows = []
            while i < n and lines[i].strip().startswith("|"):
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            th = "".join(f"<th>{md_inline(c)}</th>" for c in head)
            body_rows = "".join(
                "<tr>" + "".join(f"<td>{md_inline(c)}</td>" for c in r) + "</tr>"
                for r in rows)
            out.append(f"<div class=\"md-table\"><table><thead><tr>{th}</tr></thead>"
                       f"<tbody>{body_rows}</tbody></table></div>")
            continue

        # blockquote
        if stripped.startswith(">"):
            buf = []
            while i < n and lines[i].strip().startswith(">"):
                buf.append(lines[i].strip()[1:].strip())
                i += 1
            out.append(f"<blockquote><p>{md_inline(' '.join(buf))}</p></blockquote>")
            continue

        # lists (unordered + ordered, two levels deep)
        if re.match(r"^([-*+]|\d+\.)\s+", stripped):
            ordered = bool(re.match(r"^\d+\.", stripped))
            items, i = _read_list(lines, i, n)
            out.append(_render_list(items, ordered, 0))
            continue

        # paragraph
        buf = []
        while i < n and lines[i].strip() and not _is_block_start(lines[i]):
            buf.append(lines[i].strip())
            i += 1
        if buf:
            out.append(f"<p>{md_inline(' '.join(buf))}</p>")
        else:                       # defensive: never spin
            i += 1

    return "\n".join(out), toc


def _is_block_start(line):
    s = line.strip()
    return (s.startswith(("```", ">", "|", "#")) or
            re.match(r"^([-*+]|\d+\.)\s+", s) is not None or
            re.fullmatch(r"(-{3,}|\*{3,}|_{3,})", s) is not None)


def _read_list(lines, i, n):
    """Read a list block -> [{text, children: [...]}] (children = nested list)."""
    base = len(lines[i]) - len(lines[i].lstrip())
    items = []
    while i < n:
        raw = lines[i]
        if not raw.strip():
            # blank line ends the list only when the NEXT line is not a list line
            j = i + 1
            while j < n and not lines[j].strip():
                j += 1
            if j >= n or not re.match(r"^\s*([-*+]|\d+\.)\s", lines[j]) \
                    or (len(lines[j]) - len(lines[j].lstrip())) < base:
                break
            i += 1
            continue
        ind = len(raw) - len(raw.lstrip())
        if ind < base:
            break
        m = re.match(r"^\s*([-*+]|\d+\.)\s+(.*)$", raw)
        if not m:
            break
        if ind > base and items:
            child_lines = []
            start = i
            while i < n and (not lines[i].strip() or
                             (len(lines[i]) - len(lines[i].lstrip())) > base):
                child_lines.append(lines[i])
                i += 1
            sub, _ = _read_list(child_lines, 0, len(child_lines))
            items[-1]["children"] = sub
            if i == start:          # safety
                i += 1
            continue
        items.append({"text": m.group(2).strip(), "children": []})
        i += 1
    return items, i


def _render_list(items, ordered, depth):
    tag = "ol" if ordered else "ul"
    parts = [f"<{tag}>"]
    for it in items:
        inner = md_inline(it["text"])
        if it["children"]:
            inner += _render_list(it["children"], not ordered, depth + 1)
        parts.append(f"<li>{inner}</li>")
    parts.append(f"</{tag}>")
    return "".join(parts)


# =============================================================================
# 3. COLLECTION CONFIGURATION
# =============================================================================
# intro/lead copy for hubs: honest, evergreen, and specific about what lives
# in the section TODAY (empty collections say so rather than pretending).
HUBS = {
    "notes": {
        "file": "study-notes.html",
        "dir": "notes",
        "prefix": "note",
        "eyebrow": "Learn & Revise",
        "h1": "Study Notes for Punjab Competitive Exams",
        "title": "Punjab Exam Study Notes | House of Aspirants",
        "description": (
            "Free subject-wise study notes for Punjab Police, PSSSB and PPSC "
            "aspirants - reading time, difficulty, exam tags, table of contents "
            "and related quizzes."
        ),
        "keywords": ("Study Notes Punjab, Punjab Police notes, PSSSB study notes, "
                     "PPSC notes, free exam notes Punjabi English"),
        "lead": (
            "Every note is written by the House of Aspirants editorial team and "
            "organised the way you actually revise: one subject, one idea, one "
            "read. Notes link straight into the quiz set that tests them."
        ),
        "answer": (
            "Study notes here are free, subject-wise pages that carry reading "
            "time, difficulty and exam tags, so you know what you are opening "
            "before you start. Every note ends with related quizzes, so revising "
            "a concept and proving you remember it happens in one click."
        ),
        "empty_h3": "No notes published yet",
        "empty_p": ("The first set of notes is being written and reviewed now. "
                    "Until it lands, the study guides and daily quizzes below are "
                    "ready to use."),
        "empty_cta": ("articles.html", "Browse study guides"),
        "schema_hub": "Study Notes",
    },
    "magazine": {
        "file": "magazine.html",
        "dir": "magazine",
        "prefix": "magazine",
        "eyebrow": "Current Affairs",
        "h1": "Current Affairs Monthly Magazine",
        "title": "Current Affairs Monthly Magazine | House of Aspirants",
        "description": (
            "Monthly current affairs magazine for Punjab exam aspirants - cover, "
            "PDF download, online reading, highlights, expected MCQs and a quiz "
            "for every issue."
        ),
        "keywords": ("current affairs magazine PDF, monthly current affairs Punjab, "
                     "Punjab current affairs magazine, current affairs MCQ"),
        "lead": (
            "One issue per month, built from the events that matter to Punjab "
            "exams: a cover, a downloadable PDF, the highlights worth revising "
            "and the quiz that turns reading into marks."
        ),
        "answer": (
            "Each monthly issue ships a cover, a PDF download, an online reading "
            "version, the month's important highlights and its own quiz, so one "
            "issue covers reading, revision and recall. The archive below lists "
            "every issue that has actually been published - nothing is previewed "
            "before it exists."
        ),
        "empty_h3": "No issue published yet",
        "empty_p": ("The first monthly issue is being assembled from this month's "
                    "current affairs sets. The current affairs quizzes are already "
                    "live if you want to start there."),
        "empty_cta": ("subject.html?subject=current-affairs", "Practise current affairs"),
        "schema_hub": "Monthly Magazine",
    },
    "strategy": {
        "file": "strategy.html",
        "dir": "strategy",
        "prefix": "strategy",
        "eyebrow": "Plan & Execute",
        "h1": "Preparation Strategy for Punjab Exams",
        "title": "Exam Preparation Strategy & Study Plans | House of Aspirants",
        "description": (
            "Preparation strategy for Punjab aspirants - study plans, daily and "
            "weekly timetables, book guidance, revision, mock test and mistake "
            "analysis method."
        ),
        "keywords": ("preparation strategy Punjab, study plan Punjab Police, daily "
                     "timetable exam, revision strategy, mock test strategy"),
        "lead": (
            "Method beats motivation. This section collects the practical side of "
            "preparation: how to plan a day, how to plan a week, what to revise "
            "and how to turn a mock test score into a to-do list."
        ),
        "answer": (
            "Strategy pages cover study plans, daily and weekly timetables, book "
            "recommendations, revision cycles, mock test method, mistake analysis "
            "and time management. Each one is written to be used this week rather "
            "than someday, and every method ends in a link to free practice on "
            "this portal."
        ),
        "empty_h3": "No strategy article published yet",
        "empty_p": ("Study plans and timetable templates are being written as "
                    "reviewed articles. The four evergreen study guides already "
                    "cover the same ground today."),
        "empty_cta": ("articles.html", "Read the study guides"),
        "schema_hub": "Preparation Strategy",
    },
    "sessions": {
        "file": "live-sessions.html",
        "dir": "sessions",
        "prefix": "session",
        "eyebrow": "Weekly Live Guidance",
        "h1": "Weekly Live Guidance Sessions",
        "title": "Weekly Live Guidance Sessions | House of Aspirants",
        "description": (
            "Upcoming and past House of Aspirants live sessions - topic, date, "
            "time, platform, join link, session summary, important questions and "
            "student doubts."
        ),
        "keywords": ("live session Punjab exam, weekly live guidance, exam strategy "
                     "live class, student doubts session Punjab"),
        "lead": (
            "A live session every week: one topic, one time slot, one join link. "
            "Past sessions stay here with their summary, the questions that were "
            "discussed and the doubts students raised."
        ),
        "answer": (
            "Every session lists its topic, date, time and platform with a direct "
            "join link, then keeps a summary, the important questions discussed "
            "and the student doubts raised. Upcoming sessions appear first and "
            "past sessions stay below them, so nothing you attended disappears."
        ),
        "empty_h3": "No session scheduled yet",
        "empty_p": ("The next live session will be posted here with its date, time "
                    "and join link. Until then, the Telegram channel carries every "
                    "announcement."),
        "empty_cta": ("https://t.me/HouseOfAspirant", "Join on Telegram"),
        "schema_hub": "Live Sessions",
    },
    "recruitment": {
        "file": "recruitment.html",
        "dir": "recruitment",
        "prefix": "recruit",
        "eyebrow": "Official Sources Only",
        "h1": "Punjab Recruitment Updates & Official Notifications",
        "title": "Punjab Recruitment Updates | House of Aspirants",
        "description": (
            "Recruitment records for Punjab posts - official notification link, "
            "eligibility, syllabus, selection process, important dates and "
            "preparation links."
        ),
        "keywords": ("Punjab recruitment, Punjab Police notification, PSSSB "
                     "notification, PPSC jobs, PSPCL jobs, Patwari recruitment"),
        "lead": (
            "This section points at the recruiting body's own website and nothing "
            "else. Every record links the official notification, restates only "
            "what that notification says and links back to the preparation guide "
            "for the post."
        ),
        "answer": (
            "Recruitment pages here never invent dates, vacancies or admit cards. "
            "Each one carries the official notification link on a government "
            "domain, restates eligibility, syllabus, selection process and "
            "important dates from that notification only, and links the matching "
            "preparation guide for the post."
        ),
        "empty_h3": "No official notification published here yet",
        "empty_p": ("Notifications are added only when the recruiting body "
                    "publishes one, and only as a link to that body's own website. "
                    "The preparation guides for every post are ready below."),
        "empty_cta": ("punjab-exams.html", "See all Punjab exam guides"),
        "schema_hub": "Recruitment Updates",
    },
    "pdfs": {
        "file": "pdfs.html",
        "dir": "pdfs",
        "prefix": "",            # registry only - no per-PDF page
        "eyebrow": "Download & Study Offline",
        "h1": "Free PDFs for Punjab Exams",
        "title": "Free PDFs for Punjab Exams | House of Aspirants",
        "description": (
            "Free downloadable PDFs for Punjab exam preparation - notes, "
            "question sets and revision sheets, each with a subject, exam tags "
            "and a direct download button."
        ),
        "keywords": ("free PDF Punjab Police notes, current affairs PDF, exam "
                     "revision PDF, Punjab GK PDF"),
        "lead": (
            "Download, print, revise. Every PDF listed here is a real file hosted "
            "on this site with a direct download button - no sign-up, no email "
            "wall, no third-party redirect."
        ),
        "answer": (
            "PDFs are hosted on this site and download with one click, straight "
            "from our own storage - no sign-up, no email wall and no redirect "
            "through a third party. Each entry shows its subject and exam tags so "
            "you can grab the exact sheet you need before a commute."
        ),
        "empty_h3": "No PDF published yet",
        "empty_p": ("PDF sheets are being typeset from the notes and question "
                    "sets. Until they land, every quiz works offline once the app "
                    "is installed."),
        "empty_cta": ("quiz.html?mode=daily", "Open the daily quiz"),
        "schema_hub": "Free PDFs",
    },
}

# Front matter contract per collection: required + optional keys (used for
# validation and for the authoring guide in content/README.md).
REQUIRED_FIELDS = {
    "notes": ["title", "description", "published", "subject"],
    "magazine": ["title", "description", "published", "month"],
    "strategy": ["title", "description", "published", "category"],
    "sessions": ["title", "description", "published", "date"],
    "recruitment": ["title", "description", "published", "post", "official_url"],
    "pdfs": ["title", "description", "file"],
}
OPTIONAL_FIELDS = {
    "notes": ["updated", "author", "difficulty", "exams", "subjects", "tags",
              "pdf", "slug"],
    "magazine": ["updated", "month", "pdf", "quiz", "highlights", "tags",
                 "subjects", "cover", "cover_width", "cover_height",
                 "expected_mcqs"],
    "strategy": ["updated", "category", "difficulty", "exams", "subjects",
                 "tags", "pdf"],
    "sessions": ["updated", "date", "time", "start_time", "platform", "join",
                 "status", "questions", "doubts", "summary", "tags", "subjects"],
    "recruitment": ["updated", "post", "exam", "official_url", "official_source",
                    "eligibility", "syllabus", "selection", "dates", "pdf",
                    "expected_questions", "previous_papers", "tags", "subjects"],
    "pdfs": ["file", "subject", "exams", "tags", "note"],
}
KNOWN_EXTRA = {"slug", "title_pa", "description_pa"}


def validate_meta(coll, slug, meta, where):
    known = set(REQUIRED_FIELDS[coll]) | set(OPTIONAL_FIELDS[coll]) | KNOWN_EXTRA
    # Normalise list fields first: `exams: Punjab Police` (no brackets) is a
    # single item, not a string to be iterated character by character.
    for key in LIST_FIELDS & set(meta):
        if isinstance(meta[key], str):
            meta[key] = [meta[key]] if meta[key].strip() else []
        elif not isinstance(meta[key], list):
            err(f"{where}: {key} must be a list")
            meta[key] = []
    for key in REQUIRED_FIELDS[coll]:
        if key not in meta or meta[key] in ("", None, []):
            err(f"{where}: required front matter field {key!r} missing or empty")
    for key in meta:
        if key not in known:
            warn(f"{where}: unknown front matter field {key!r} (ignored)")

    title = str(meta.get("title", ""))
    if title and len(title) > 60:
        err(f"{where}: title is {len(title)} chars, the site limit is 60")
    desc = str(meta.get("description", ""))
    if desc and not (140 <= len(desc) <= 160):
        err(f"{where}: description is {len(desc)} chars, the site range is 140-160 "
            f"characters (got: {desc[:70]!r}...)")
    for dkey in ("published", "updated", "date"):
        if meta.get(dkey) and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(meta[dkey])):
            err(f"{where}: {dkey} must be YYYY-MM-DD (got {meta[dkey]!r})")
    if coll == "recruitment" and meta.get("official_url") and \
            not official_url_ok(str(meta["official_url"])):
        err(f"{where}: official_url must be a government domain "
            f"(.gov.in / .nic.in / pspcl) - got {meta['official_url']!r}")
    if meta.get("pdf") and not (ROOT / str(meta["pdf"])).exists():
        err(f"{where}: pdf file not found at {meta['pdf']!r}")
    if meta.get("quiz") and not (ROOT / str(meta["quiz"])).exists():
        err(f"{where}: quiz file not found at {meta['quiz']!r}")
    if meta.get("cover") and not (ROOT / str(meta["cover"])).exists():
        err(f"{where}: cover image not found at {meta['cover']!r}")
    for dkey in ("cover_width", "cover_height"):
        if meta.get(dkey) and not str(meta[dkey]).isdigit():
            err(f"{where}: {dkey} must be a positive integer (got {meta[dkey]!r})")
    if meta.get("join") and not re.fullmatch(
            r"https://[^\s]+", str(meta["join"])):
        err(f"{where}: join must be an https:// URL (got {meta['join']!r})")
    if meta.get("file") and not (ROOT / str(meta["file"])).exists():
        err(f"{where}: file not found at {meta['file']!r} (add it or remove the record)")
    subj = str(meta.get("subject", ""))
    if subj and subj not in SUBJECT_IDS:
        err(f"{where}: unknown subject id {subj!r} (known: {', '.join(sorted(SUBJECT_IDS))})")
    for s in as_list(meta.get("subjects")):
        if str(s) not in SUBJECT_IDS:
            err(f"{where}: unknown subject id {s!r} (known: "
                f"{', '.join(sorted(SUBJECT_IDS))})")


def official_url_ok(url):
    m = re.match(r"^https?://([^/]+)", url.strip())
    if not m:
        return False
    host = m.group(1).lower().split(":")[0]
    if host.startswith("www."):
        host = host[4:]
    return host in OFFICIAL_HOSTS or host.endswith(OFFICIAL_HOST_SUFFIXES)


# =============================================================================
# 4. PAGE SCAFFOLD  (head + chrome hooks - mirrors the hand-written pages so
#                    seo_check treats generated pages exactly like the rest)
# =============================================================================
def head(title, desc, keywords, url, og_type, jsonld, lang="en"):
    return f"""<!DOCTYPE html>
<!-- {GENERATED_MARKER} -->
<html lang="{lang}" data-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(desc)}">
  <meta name="keywords" content="{esc(keywords)}">
  <meta name="robots" content="index, follow">
  <meta name="theme-color" content="#4f46e5">
  <link rel="canonical" href="{esc(url)}">
  <meta property="og:type" content="{og_type}">
  <meta property="og:site_name" content="House of Aspirants">
  <meta property="og:url" content="{esc(url)}">
  <meta property="og:title" content="{esc(title)}">
  <meta property="og:description" content="{esc(desc)}">
  <meta property="og:image" content="{OG_ABS}">
  <meta property="og:locale" content="en_IN">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{esc(title)}">
  <meta name="twitter:description" content="{esc(desc)}">
  <meta name="twitter:image" content="{OG_ABS}">
  <link rel="icon" href="assets/img/favicon-32.png" type="image/png" sizes="32x32">
  <link rel="apple-touch-icon" sizes="180x180" href="assets/img/icon-180.png">
  <link rel="manifest" href="manifest.webmanifest">
  <link rel="preconnect" href="https://t.me">
  <link rel="dns-prefetch" href="//t.me">
  <link rel="dns-prefetch" href="//instagram.com">
  <link rel="dns-prefetch" href="//youtube.com">
  <link rel="preload" href="assets/css/style.css" as="style">
  <link rel="stylesheet" href="assets/css/style.css">
  <link rel="preload" href="assets/img/logo-sm.png" as="image" type="image/png">
  <script type="application/ld+json">
{jsonld}
  </script>
</head>
<body data-page="{og_page_key(url)}">
  <div data-site-header></div>
"""


def og_page_key(url):
    """body data-page key used for nav highlighting (matches data-nav keys)."""
    path = url.replace(DOMAIN, "")
    for key, prefix in (("notes", "/note"), ("magazine", "/magazine"),
                        ("strategy", "/strategy"), ("sessions", "/session"),
                        ("recruitment", "/recruit")):
        if path.startswith(prefix):
            return key
    if path.startswith("/study-notes"):
        return "notes"
    if path.startswith("/live-sessions"):
        return "sessions"
    if path.startswith("/pdfs"):
        return "pdfs"
    return path.strip("/") or "home"


TAIL = """
  <div data-site-footer></div>

  <script src="assets/js/core.js" defer></script>
  <script src="assets/js/auth.js" defer></script>
  <script src="assets/js/content.js" defer></script>
</body>
</html>
"""


def breadcrumb_jsonld(crumbs):
    items = []
    for pos, (name, u) in enumerate(crumbs, 1):
        node = {"@type": "ListItem", "position": pos, "name": name}
        if u:
            node["item"] = u
        items.append(node)
    return json.dumps(items, ensure_ascii=False, indent=2)


def graph(nodes):
    body = ",\n".join("    " + json.dumps(n, ensure_ascii=False, indent=2).replace("\n", "\n    ")
                      for n in nodes)
    return ('  {\n    "@context": "https://schema.org",\n    "@graph": [\n'
            + body + "\n    ]\n  }")


def webpage_node(url, name, description, breadcrumb_id, kind="WebPage"):
    node = {
        "@type": kind,
        "@id": f"{url}#webpage",
        "name": name,
        "url": url,
        "description": description,
        "inLanguage": "en-IN",
        "isPartOf": {"@id": f"{DOMAIN}/#website"},
        "breadcrumb": {"@id": breadcrumb_id},
    }
    return node


def article_node(rec, url):
    node = {
        "@type": ["Article", "WebPage"],
        "@id": f"{url}#webpage",
        "name": rec["title"],
        "url": url,
        "headline": rec["title"],
        "description": rec["description"],
        "image": {
            "@type": "ImageObject",
            "@id": f"{OG_ABS}#image",
            "url": OG_ABS,
            "width": 1200,
            "height": 630,
        },
        "datePublished": rec["published"],
        "dateModified": rec.get("updated") or rec["published"],
        "inLanguage": "en-IN",
        "author": {
            "@type": "Organization",
            "name": rec.get("author") or BYLINE,
            "url": f"{DOMAIN}/about",
            "logo": {
                "@type": "ImageObject",
                "url": f"{DOMAIN}/assets/img/logo-sm.png",
                "width": 120,
                "height": 120,
            },
        },
        "publisher": {"@id": f"{DOMAIN}/#organization"},
        "isPartOf": {"@id": f"{DOMAIN}/#website"},
        "breadcrumb": {"@id": f"{url}#breadcrumb"},
        "mainEntityOfPage": {"@id": f"{url}#webpage"},
    }
    return node


def breadcrumb_node(crumbs):
    return {
        "@type": "BreadcrumbList",
        "@id": crumbs["id"],
        "itemListElement": json.loads(breadcrumb_jsonld(crumbs["items"])),
    }


# =============================================================================
# 5. CONTENT LOADING
# =============================================================================
def load_subject_ids():
    try:
        data = json.loads((ROOT / "data" / "subjects.json").read_text(encoding="utf-8"))
        return {s["id"] for s in data.get("subjects", [])}
    except Exception as e:                     # pragma: no cover
        err(f"data/subjects.json unreadable: {e}")
        return set()


SUBJECT_IDS = load_subject_ids()


def load_index():
    try:
        return json.loads((ROOT / "data" / "index.json").read_text(encoding="utf-8"))
    except Exception as e:                     # pragma: no cover
        err(f"data/index.json unreadable: {e}")
        return {"subjects": []}


def load_quiz_landing():
    """(subject_id, topic_id) -> extensionless landing path, when built."""
    out = {}
    try:
        man = json.loads((ROOT / "data" / "landing-manifest.json")
                         .read_text(encoding="utf-8"))
    except Exception:
        return out
    for p in man.get("pages", []):
        if p.get("type") == "quiz" and "/" in str(p.get("entity", "")):
            s, t = p["entity"].split("/", 1)
            out[(s, t)] = p.get("url", "").replace(DOMAIN, "")
    return out


def read_variant(coll_dir, slug, pa):
    """Read `<slug>.md` (English) and, when present, `<slug>.pa.md` (Punjabi)."""
    suffix = ".pa.md" if pa else ".md"
    path = coll_dir / f"{slug}{suffix}"
    return path if path.exists() else None


def build_record(coll, cfg, slug, path, index, lang):
    where = str(path.relative_to(ROOT))
    try:
        raw = path.read_text(encoding="utf-8")
        meta, body = parse_front_matter(raw, where)
    except ValueError as e:
        err(str(e))
        return None
    except UnicodeDecodeError:
        err(f"{where}: not valid UTF-8")
        return None

    validate_meta(coll, slug, meta, where)
    if errors:
        return None

    prefix = cfg["prefix"]
    # A Punjabi variant file carries its OWN front matter (Gurmukhi title and
    # description), so it is validated and rendered exactly like the English
    # original - Punjabi-first, with English one tap away on both pages.
    page_slug = str(meta.get("slug") or slug)
    filename, url = "", ""
    if prefix:
        filename = f"{prefix}-{page_slug}{'-pa' if lang == 'pa' else ''}.html"
        url = f"{DOMAIN}/{filename[:-5]}"

    title = str(meta.get("title", ""))
    desc = str(meta.get("description", ""))

    html_body, toc = md_to_html(body)
    words = len(re.sub(r"<[^>]+>", " ", html_body).split())
    reading = max(1, -(-words // 200))          # ceil at 200 wpm, never "0 min"
    subjects = [str(s) for s in (meta.get("subjects") or
                                 ([meta["subject"]] if meta.get("subject") else []))]
    subjects = [s for s in subjects if s in SUBJECT_IDS]

    record = {
        "collection": coll,
        "file": filename,
        "url": url,
        "path": str(path.relative_to(ROOT)),
        "title": title,
        "description": desc,
        "published": str(meta.get("published") or meta.get("date") or ""),
        "updated": str(meta.get("updated") or meta.get("published") or meta.get("date") or ""),
        "subjects": subjects,
        "tags": [str(t) for t in (meta.get("tags") or [])],
        "exams": [str(t) for t in (meta.get("exams") or [])],
        "readingMinutes": reading,
        "wordCount": words,
        "lang": lang,
        "meta": meta,
        "bodyHtml": html_body,
        "toc": toc,
        "slug": page_slug,
    }
    for extra in ("difficulty", "category", "month", "date", "time", "platform",
                  "status", "post", "official_url", "official_source", "exam",
                  "file", "pdf", "quiz", "join", "start_time"):
        if meta.get(extra) not in (None, "", []):
            record[extra] = meta[extra]
    return record


def subject_name(index, sid):
    s = next((x for x in index.get("subjects", []) if x.get("id") == sid), None)
    return (s or {}).get("name") or sid.replace("-", " ").title()


def related_quizzes(record, index, landing, limit=3):
    out = []
    for sid in record["subjects"]:
        subj = next((s for s in index.get("subjects", []) if s["id"] == sid), None)
        if not subj:
            continue
        for t in subj.get("topics", []):
            if not t.get("available"):
                continue
            path = landing.get((sid, t["id"])) or \
                f"quiz.html?subject={sid}&topic={t['id']}"
            href = path.lstrip("/") + ".html" if path.startswith("/quiz-") else path
            out.append({
                "title": t.get("name", ""),
                "href": href,
                "subject": subj.get("name", ""),
            })
            if len(out) >= limit:
                return out
    return out


def related_notes(record, pool, limit=3):
    out = []
    for other in pool:
        if other["file"] == record["file"]:
            continue
        if other.get("lang") != record.get("lang"):
            continue
        shared = set(other["subjects"]) & set(record["subjects"]) or \
            set(other["tags"]) & set(record["tags"])
        if not shared:
            continue
        out.append(other)
        if len(out) >= limit:
            break
    return out


# =============================================================================
# 6. ITEM PAGE RENDERING
# =============================================================================
def badge_row(record):
    bits = []
    meta = record.get("meta", {})
    coll = record.get("collection", "")
    # Collection-specific facts go first: an issue leads with its month, a live
    # session with its slot, a recruitment record with the body that issued it.
    if coll == "magazine" and record.get("month"):
        bits.append(f'<span class="badge">Issue {esc(str(record["month"]))}</span>')
    if coll == "sessions":
        if record.get("date"):
            bits.append(f'<span class="badge">{esc(fmt_date(str(record["date"])))}</span>')
        for key, label in (("time", "Time"), ("platform", "Platform")):
            if record.get(key):
                bits.append(f'<span class="badge">{esc(str(record[key]))}</span>')
        if record.get("status"):
            bits.append('<span class="badge badge-muted">'
                        f'{"Upcoming" if str(record["status"]) == "upcoming" else "Past session"}'
                        '</span>')
    if coll == "recruitment" and record.get("official_source"):
        bits.append(f'<span class="badge">Official · {esc(str(record["official_source"]))}</span>')
    if coll == "strategy" and meta.get("category"):
        bits.append(f'<span class="badge badge-muted">{esc(str(meta["category"]))}</span>')
    if record.get("readingMinutes"):
        bits.append(f'<span class="badge badge-muted">{record["readingMinutes"]} min read</span>')
    if record.get("difficulty"):
        bits.append(f'<span class="badge badge-muted">{esc(str(record["difficulty"]))}</span>')
    for exam in record.get("exams", [])[:4]:
        bits.append(f'<span class="badge badge-muted">{esc(exam)}</span>')
    for tag in record.get("tags", [])[:4]:
        bits.append(f'<span class="badge badge-muted">{esc(tag)}</span>')
    return f'<div class="doc-badges">{"".join(bits)}</div>' if bits else ""


def share_row(url, title):
    q = f"?url={url}&text={title}"
    return f"""<div class="share-row" data-share-url="{esc(url)}">
          <span class="share-label">Share</span>
          <a class="share-btn" data-share="copy" href="{esc(url)}" role="button">🔗 Copy link</a>
          <a class="share-btn" href="https://wa.me/{q}" target="_blank" rel="noopener">WhatsApp</a>
          <a class="share-btn" href="https://t.me/share/url{q}" target="_blank" rel="noopener">Telegram</a>
          <a class="share-btn" href="https://twitter.com/intent/tweet{q}" target="_blank" rel="noopener">X</a>
        </div>"""


def prev_next(record, pool):
    """pool is already sorted newest-first -> prev = older, next = newer."""
    idx = next((i for i, r in enumerate(pool) if r["file"] == record["file"]), None)
    if idx is None:
        return "", ""
    older = pool[idx + 1] if idx + 1 < len(pool) else None
    newer = pool[idx - 1] if idx > 0 else None

    def card(r, kind):
        if not r:
            return '<span class="pn-card pn-empty"></span>'
        arrow = "← Newer" if kind == "next" else "Older →"
        return (f'<a class="pn-card" href="{r["file"]}">'
                f'<span class="pn-label">{arrow}</span>'
                f'<span class="pn-title">{esc(r["title"])}</span></a>')

    return card(older, "prev"), card(newer, "next")


def render_item(record, cfg, pool, index, landing):
    url = record["url"]
    hub = HUBS[record["collection"]]
    hub_url = f"{DOMAIN}/{hub['file'][:-5]}"

    # Article also carries the WebPage type, so one node covers both rules and
    # there is never a duplicate @id on the page.
    crumbs = {"id": f"{url}#breadcrumb",
              "items": [("Home", f"{DOMAIN}/"),
                        (hub["schema_hub"], hub_url),
                        (record["title"], url)]}
    nodes = [article_node(record, url), breadcrumb_node(crumbs)]

    if record["collection"] == "sessions" and record.get("start_time") and \
            record.get("date"):
        nodes.insert(1, {
            "@type": "Event",
            "@id": f"{url}#event",
            "name": record["title"],
            "description": record["description"],
            "startDate": f'{record["date"]}T{record["start_time"]}:00+05:30',
            "eventAttendanceMode": "OnlineEventAttendance",
            "url": url,
        })

    jsonld = graph(nodes)

    # ---- hero -------------------------------------------------------------
    eyebrow_bits = []
    if record["collection"] == "notes":
        names = [subject_name(index, s) for s in record["subjects"]]
        eyebrow_bits.append(" · ".join(names) if names else "Study Note")
    elif record["collection"] == "magazine":
        eyebrow_bits.append(f"Monthly issue · {record.get('month', '')}".strip(" ·"))
    elif record["collection"] == "strategy":
        eyebrow_bits.append(str(record.get("category", "Strategy")))
    elif record["collection"] == "sessions":
        state = "Upcoming session" if str(record.get("status", "")) == "upcoming" \
            else "Past session"
        eyebrow_bits.append(f'{state} · {record.get("date", "")}')
    elif record["collection"] == "recruitment":
        eyebrow_bits.append(str(record.get("official_source", "Official notification")))

    meta_line = []
    if record.get("published"):
        meta_line.append(f'Published {fmt_date(record["published"])}')
    if record.get("updated") and record["updated"] != record.get("published"):
        meta_line.append(f'Updated {fmt_date(record["updated"])}')

    pdf_html = ""
    if record.get("pdf"):
        pdf_html = (f'<a class="btn btn-primary" href="{esc(str(record["pdf"]))}" '
                    f'download>⬇ Download PDF</a>')

    switch_html = ""
    sibling = ROOT / "content" / cfg["dir"] / (
        record["slug"] + (".md" if record["lang"] == "pa" else ".pa.md"))
    if sibling.exists():
        if record["lang"] == "pa":
            switch_html = (f'<a class="badge badge-lang" '
                           f'href="{cfg["prefix"]}-{record["slug"]}.html" '
                           f'hreflang="en">English version</a>')
        else:
            switch_html = (f'<a class="badge badge-lang" lang="pa" hreflang="pa" '
                           f'href="{cfg["prefix"]}-{record["slug"]}-pa.html">'
                           f'ਪੰਜਾਬੀ ਵਿੱਚ ਪੜ੍ਹੋ</a>')

    toc_html = ""
    if len(record["toc"]) >= 2:
        items = "".join(f'<li><a href="#{a}">{esc(t)}</a></li>'
                        for a, t in record["toc"])
        toc_head = {"notes": "In this note", "magazine": "In this issue",
                    "strategy": "In this guide", "sessions": "On this page",
                    "recruitment": "On this page"}.get(record["collection"],
                                                       "In this page")
        toc_html = (f'<aside class="doc-toc" aria-label="Table of contents">'
                    f'<h2>{toc_head}</h2><ol>{items}</ol></aside>')

    byline_meta = " · ".join(meta_line)
    byline = f"""<div class="byline">
          <span class="bl-avatar" aria-hidden="true">HA</span>
          <div class="bl-body">
            <span class="bl-label">Written &amp; reviewed by</span>
            <span class="bl-name">{esc(str(record.get("author") or BYLINE))}</span>
            <span class="bl-meta">{esc(byline_meta or "Reviewed by the editorial team")}</span>
          </div>
        </div>"""

    # ---- body sections ----------------------------------------------------
    sections = []
    front = ""
    coll = record["collection"]

    if coll == "magazine":
        front = issue_front(record)          # cover + issue actions, above the text
        sections.append(magazine_sections(record))
    elif coll == "sessions":
        front = session_front(record)        # date / time / platform / join link
        sections.append(session_sections(record))
    elif coll == "recruitment":
        sections.append(recruitment_sections(record))

    quizzes = related_quizzes(record, index, landing)
    if quizzes:
        cards = "".join(
            f'<a class="card card-pad reveal" href="{esc(q["href"])}">'
            f'<span class="eyebrow">{esc(q["subject"])}</span>'
            f'<h3>{esc(q["title"])}</h3>'
            f'<p class="ilink">Start the quiz →</p></a>'
            for q in quizzes)
        quiz_head = ("Related current affairs" if coll == "magazine"
                     else "Test yourself on this")
        sections.append(f"""<section class="section" style="padding-top:0">
        <div class="container">
          <div class="section-head reveal"><div>
            <span class="eyebrow">Practice</span>
            <h2>{quiz_head}</h2>
          </div></div>
          <div class="grid grid-3">{cards}</div>
        </div>
      </section>""")
    else:
        # No matching set exists yet for this subject. Say so honestly instead
        # of dressing up unrelated quizzes as "related".
        sections.append(f"""<section class="section" style="padding-top:0">
        <div class="container">
          <div class="section-head reveal"><div>
            <span class="eyebrow">Practice</span>
            <h2>Practise while it is fresh</h2>
            <p>No dedicated set for this subject yet - the daily challenge and
               the full mock are always live.</p>
          </div></div>
          <div class="grid grid-3">
            <a class="card card-pad reveal" href="quiz.html?mode=daily">
              <span class="eyebrow">Daily</span><h3>Today's Daily Challenge</h3>
              <p class="ilink">Start the quiz →</p></a>
            <a class="card card-pad reveal" href="index.html#subjects">
              <span class="eyebrow">All subjects</span><h3>Pick a subject to drill</h3>
              <p class="ilink">Browse subjects →</p></a>
            <a class="card card-pad reveal" href="mock.html">
              <span class="eyebrow">Full paper</span><h3>Take a mock test</h3>
              <p class="ilink">Open mock tests →</p></a>
          </div>
        </div>
      </section>""")

    notes = related_notes(record, pool)
    if notes:
        cards = "".join(
            f'<a class="card card-pad reveal" href="{n["file"]}">'
            f'<span class="eyebrow">Study note</span>'
            f'<h3>{esc(n["title"])}</h3>'
            f'<p class="muted">{esc(n["description"])}</p>'
            f'<p class="ilink">{n["readingMinutes"]} min read →</p></a>'
            for n in notes)
        sections.append(f"""<section class="section" style="padding-top:0">
        <div class="container">
          <div class="section-head reveal"><div>
            <span class="eyebrow">Keep going</span>
            <h2>Related notes</h2>
          </div></div>
          <div class="grid grid-3">{cards}</div>
        </div>
      </section>""")

    prev_card, next_card = prev_next(record, pool)
    sections.append(f"""<section class="section" style="padding-top:0">
      <div class="container">
        <nav class="prev-next" aria-label="Previous and next note">{prev_card}{next_card}</nav>
      </div>
    </section>""")

    # ---- assemble ---------------------------------------------------------
    toc_slot = toc_html or ""
    html = head(record["title"], record["description"],
                keywords_for(record), url, "article", jsonld,
                lang="pa" if record["lang"] == "pa" else "en")
    html += f"""  <main id="main">
    <section class="page-hero">
      <div class="container">
        <nav class="breadcrumb" aria-label="Breadcrumb">
          <a href="index.html">Home</a><span>/</span>
          <a href="{hub['file']}">{esc(hub["schema_hub"])}</a><span>/</span>
          <span>{esc(record["title"])}</span>
        </nav>
        <span class="eyebrow">{esc(" · ".join(eyebrow_bits) or hub["eyebrow"])}</span>
        <h1>{esc(record["title"])}</h1>
        {badge_row(record)}
        <div class="answer-box">
          <span class="ab-label">Quick answer</span>
          <p>{esc(record["description"])}</p>
        </div>
        {byline}
        <div class="doc-actions">{pdf_html}{switch_html}</div>
        {share_row(url, record["title"])}
      </div>
    </section>
{front}
    <section class="section" style="padding-top:0" id="read">
      <div class="container doc-layout">
        {toc_slot}
        <article class="doc-body prose">
{record["bodyHtml"]}
        </article>
      </div>
    </section>
{"".join(sections)}
  </main>
"""
    html += TAIL
    return html, jsonld


def recruitment_sections(record):
    """Notification / eligibility / syllabus / selection / dates / strategy /
    expected questions / previous papers - each block renders only when the
    Markdown actually provides it (no invented content, ever)."""
    blocks = []

    def block(title, inner, eyebrow="Recruitment details"):
        return f"""<section class="section" style="padding-top:0">
        <div class="container">
          <div class="section-head reveal"><div>
            <span class="eyebrow">{eyebrow}</span>
            <h2>{esc(title)}</h2>
          </div></div>
          {inner}
        </div>
      </section>"""

    off = str(record.get("official_url", ""))
    src = str(record.get("official_source", "the recruiting body's website"))
    notif = f"""<div class="card card-pad">
          <p class="muted">Official notification - read it on {esc(src)}'s own
             website. Dates, vacancies and admit cards below are copied from that
             notification only and are never published from any other source.</p>
          <p class="btn-row" style="margin-top:14px">
            <a class="btn btn-primary" href="{esc(off)}" target="_blank" rel="noopener">Open official notification ↗</a>
            <a class="btn btn-soft" href="punjab-exams.html">Preparation guide</a>
          </p>
        </div>"""
    blocks.append(block("Notification", notif, "Official source"))

    if record["meta"].get("eligibility"):
        blocks.append(block("Eligibility",
                            f'<div class="prose">{md_to_html(str(record["meta"]["eligibility"]))[0]}</div>'))
    if record["meta"].get("syllabus"):
        blocks.append(block("Syllabus", list_html(record["meta"]["syllabus"])))
    if record["meta"].get("selection"):
        blocks.append(block("Selection Process", list_html(record["meta"]["selection"])))
    if record["meta"].get("dates"):
        rows = "".join(f"<li>{md_inline(str(d))}</li>" for d in as_list(record["meta"]["dates"]))
        blocks.append(block("Important Dates",
                            f'<div class="prose"><ul>{rows}</ul></div>',
                            "From the official notification"))
    if record["meta"].get("expected_questions"):
        blocks.append(block("Expected Questions",
                            list_html(record["meta"]["expected_questions"]),
                            "Practice focus"))
    if record["meta"].get("previous_papers"):
        blocks.append(block("Previous Papers",
                            list_html(record["meta"]["previous_papers"])))
    return "".join(blocks)


def section_block(title, inner, eyebrow="Details"):
    """Shared section shell for the collection-specific blocks below."""
    return f"""<section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal"><div>
          <span class="eyebrow">{esc(eyebrow)}</span>
          <h2>{esc(title)}</h2>
        </div></div>
        {inner}
      </div>
    </section>"""


def issue_front(record):
    """Cover + issue actions, placed between the hero and the online reading.
    Nothing is rendered unless the Markdown ships it: no cover file, no cover;
    no linked quiz, no quiz button."""
    meta = record["meta"]
    cover = str(meta.get("cover", ""))
    quiz = str(meta.get("quiz", ""))
    if not cover and not quiz:
        return ""

    img = ""
    if cover:
        # seo_check requires width+height on every <img>; unknown covers keep a
        # stable 3:4 box (object-fit crops) so the layout never jumps.
        w = int(str(meta.get("cover_width") or 320))
        h = int(str(meta.get("cover_height") or 448))
        img = (f'<img class="doc-cover" src="{esc(cover)}" alt="Cover of '
               f'{esc(record["title"])}" width="{w}" height="{h}" decoding="async" '
               f'style="aspect-ratio:{w} / {h}">')

    buttons = ['<a class="btn btn-primary" href="#read">Read online</a>']
    if quiz:
        buttons.append(f'<a class="btn btn-soft" href="{esc(quiz)}">'
                       f'Attempt the issue MCQs</a>')
    buttons.append(f'<a class="btn btn-soft" href="{HUBS["magazine"]["file"]}">'
                   f'All issues</a>')

    facts = []
    if record.get("month"):
        facts.append(("Issue", str(record["month"])))
    if record.get("published"):
        facts.append(("Published", fmt_date(str(record["published"]))))
    if record.get("updated") and record.get("updated") != record.get("published"):
        facts.append(("Updated", fmt_date(str(record["updated"]))))
    rows = "".join(f'<div class="doc-fact"><dt>{esc(k)}</dt><dd>{esc(v)}</dd></div>'
                   for k, v in facts)

    return f"""    <section class="section" style="padding-top:0">
      <div class="container">
        <div class="card card-pad doc-issue">
          {img}
          <div class="doc-issue-body">
            <span class="eyebrow">This issue</span>
            <dl class="doc-facts">{rows}</dl>
            <div class="btn-row">{"".join(buttons)}</div>
          </div>
        </div>
      </div>
    </section>
"""


def magazine_sections(record):
    """After the reading: the issue's highlights and its expected MCQs, each
    rendered only when the Markdown lists them."""
    meta = record["meta"]
    out = []
    if meta.get("highlights"):
        out.append(section_block("Important highlights",
                                 list_html(meta["highlights"]),
                                 "The month at a glance"))
    if meta.get("expected_mcqs"):
        out.append(section_block("Most expected MCQs",
                                 list_html(meta["expected_mcqs"]),
                                 "From this issue"))
    return "".join(out)


def session_front(record):
    """Date, time, platform and the join link - what a student needs before the
    reading starts. Built only from front matter that exists."""
    facts = []
    if record.get("date"):
        facts.append(("Date", fmt_date(str(record["date"]))))
    for key, label in (("time", "Time"), ("platform", "Platform")):
        if record.get(key):
            facts.append((label, str(record[key])))
    if record.get("status"):
        facts.append(("Status", "Upcoming" if str(record["status"]) == "upcoming"
                      else "Held"))
    join = str(record.get("join", ""))
    if not facts and not join:
        return ""

    rows = "".join(f'<div class="doc-fact"><dt>{esc(k)}</dt><dd>{esc(v)}</dd></div>'
                   for k, v in facts)
    buttons = ""
    if join:
        buttons = (f'<a class="btn btn-primary" href="{esc(join)}" '
                   f'target="_blank" rel="noopener">Join the session ↗</a>')
    buttons += f'<a class="btn btn-soft" href="{HUBS["sessions"]["file"]}">All sessions</a>'

    return f"""    <section class="section" style="padding-top:0">
      <div class="container">
        <div class="card card-pad doc-issue">
          <div class="doc-issue-body">
            <span class="eyebrow">Session details</span>
            <dl class="doc-facts">{rows}</dl>
            <div class="btn-row">{buttons}</div>
          </div>
        </div>
      </div>
    </section>
"""


def session_sections(record):
    """Summary, the questions that mattered and the doubts raised - written by
    the editorial team after the session, never before."""
    meta = record["meta"]
    out = []
    if meta.get("summary"):
        body = md_to_html(str(meta["summary"]))[0]
        out.append(section_block("Session summary", f'<div class="prose">{body}</div>',
                                 "What we covered"))
    if meta.get("questions"):
        out.append(section_block("Important questions discussed",
                                 list_html(meta["questions"]), "Discuss these again"))
    if meta.get("doubts"):
        out.append(section_block("Student doubts", list_html(meta["doubts"]),
                                 "Answered live"))
    return "".join(out)


def as_list(v):
    if v is None:
        return []
    return v if isinstance(v, list) else [v]


def list_html(v):
    items = "".join(f"<li>{md_inline(str(x))}</li>" for x in as_list(v))
    return f'<div class="prose"><ul>{items}</ul></div>'


def fmt_date(iso):
    try:
        y, m, d = iso.split("-")
        months = ["January", "February", "March", "April", "May", "June", "July",
                  "August", "September", "October", "November", "December"]
        return f"{int(d)} {months[int(m) - 1]} {y}"
    except Exception:
        return str(iso)


def keywords_for(record):
    bits = []
    bits += record.get("exams", [])[:3]
    bits += [t.title() for t in record.get("tags", [])[:4]]
    bits += [s.replace("-", " ").title() for s in record.get("subjects", [])[:2]]
    bits.append("Punjab exam notes")
    bits.append("House of Aspirants")
    return ", ".join(dict.fromkeys(bits))[:300]


# =============================================================================
# 7. HUB RENDERING
# =============================================================================
def hub_cards(coll, items, index, lang="en"):
    cards = []
    for r in items:
        if coll == "pdfs":
            path = str(r["meta"].get("file", ""))
            cards.append(f'<div class="card card-pad">'
                         f'<span class="eyebrow">PDF download</span>'
                         f'<h3>{esc(r["title"])}</h3>'
                         f'<p class="muted">{esc(r["description"])}</p>'
                         f'<p class="btn-row" style="margin-top:14px">'
                         f'<a class="btn btn-primary" href="{esc(path)}" download>'
                         f'⬇ Download PDF</a></p></div>')
            continue
        eyebrow = {
            "notes": (subject_name(index, r["subjects"][0]) if r["subjects"]
                      else "Study note"),
            "magazine": f'Issue {r.get("month", "")}',
            "strategy": str(r.get("category", "Strategy")),
            "sessions": f'{r.get("date", "")} · {r.get("platform", "")}'.strip(" ·"),
            "recruitment": str(r.get("official_source", "Official notification")),
        }[coll]
        if coll == "notes":
            meta = f'{r["readingMinutes"]} min read'
        elif coll == "sessions":
            meta = "Upcoming" if str(r.get("status", "")) == "upcoming" else "Past"
        else:
            meta = "Read more"
        cards.append(
            f'<a class="card card-pad reveal" href="{r["file"]}"'
            + (' lang="pa"' if r["lang"] == "pa" else "") + '>'
            f'<span class="eyebrow">{esc(eyebrow)}</span>'
            f'<h3>{esc(r["title"])}</h3>'
            f'<p class="muted">{esc(r["description"])}</p>'
            f'<p class="ilink">{esc(meta)} →</p>'
            f'</a>')
    return "".join(cards)


def hub_page(coll, cfg, items, index, exams):
    hub = HUBS[coll]
    url = f"{DOMAIN}/{hub['file'][:-5]}"
    kinds = {"notes": "note-", "magazine": "magazine-", "strategy": "strategy-",
             "sessions": "session-", "recruitment": "recruit-", "pdfs": ""}[coll]
    live = [r for r in items if r["file"].startswith(kinds)] if kinds else items
    # The PDF hub is a registry (the PDF itself is the artifact - there is no
    # per-document page to list), so it ships as a plain WebPage, never as an
    # ItemList of URLs that do not exist.
    is_registry = (coll == "pdfs")

    crumbs = {"id": f"{url}#breadcrumb",
              "items": [("Home", f"{DOMAIN}/"), (hub["schema_hub"], url)]}
    page_node = webpage_node(url, hub["title"], hub["description"],
                             f"{url}#breadcrumb",
                             "CollectionPage" if (live and not is_registry)
                             else "WebPage")
    nodes = [page_node, breadcrumb_node(crumbs)]
    if live and not is_registry:
        nodes.insert(1, {
            "@type": "ItemList",
            "@id": f"{url}#list",
            "name": f'House of Aspirants {hub["schema_hub"]}',
            "numberOfItems": len(live),
            "itemListElement": [
                {"@type": "ListItem", "position": i + 1, "name": r["title"],
                 "item": r["url"]}
                for i, r in enumerate(live)
            ],
        })
        page_node["mainEntity"] = {"@id": f"{url}#list"}

    sections = []

    # --- primary listing ---------------------------------------------------
    if live:
        head_html = f"""<div class="section-head reveal"><div>
            <span class="eyebrow">Published</span>
            <h2>{"Latest notes" if coll == "notes" else "All published"}</h2>
            <p>{esc(hub["lead"])}</p>
          </div></div>
          <div class="grid grid-3">{hub_cards(coll, live, index)}</div>"""
    else:
        cta_href, cta_text = hub["empty_cta"]
        head_html = f"""<div class="section-head reveal"><div>
            <span class="eyebrow">Publishing pipeline</span>
            <h2>{esc(hub["empty_h3"])}</h2>
          </div></div>
          <div class="empty-state">
            <span class="es-icon" aria-hidden="true">✍️</span>
            <h3>{esc(hub["empty_h3"])}</h3>
            <p>{esc(hub["empty_p"])}</p>
            <p class="btn-row" style="justify-content:center">
              <a class="btn btn-soft" href="{esc(cta_href)}">{esc(cta_text)}</a>
            </p>
          </div>"""
    sections.append(f"""<section class="section">
      <div class="container">{head_html}</div>
    </section>""")

    # --- collection-specific extras (always real links, never invented) ----
    if coll == "notes":
        guides = []
        guides_path = ROOT / "data" / "articles.json"
        if guides_path.exists():
            try:
                guides = json.loads(guides_path.read_text(encoding="utf-8")).get("articles", [])
            except Exception as e:
                warn(f"data/articles.json unreadable: {e}")
        cards = "".join(
            f'<a class="card card-pad reveal" href="{esc(a["url"])}">'
            f'<span class="eyebrow">Study guide</span><h3>{esc(a["title"])}</h3>'
            f'<p class="muted">{esc(a["description"])}</p>'
            f'<p class="ilink">Read guide →</p></a>' for a in guides[:4])
        if cards:
            sections.append(f"""<section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal"><div>
          <span class="eyebrow">Evergreen</span>
          <h2>Study guides to start with</h2>
          <p>Long-form guides that pair with the notes as they publish.</p>
        </div><a class="btn btn-soft" href="articles.html">All study guides</a></div>
        <div class="grid grid-3">{cards}</div>
      </div>
    </section>""")

    elif coll == "magazine":
        ca = next((s for s in index.get("subjects", []) if s["id"] == "current-affairs"), None)
        if ca:
            cards = "".join(
                f'<a class="card card-pad reveal" href="{quiz_href(t)}">'
                f'<span class="eyebrow">Current affairs set</span>'
                f'<h3>{esc(t.get("name", ""))}</h3>'
                f'<p class="ilink">{t.get("count", 0)} MCQs →</p></a>'
                for t in ca.get("topics", []) if t.get("available")) 
            sections.append(f"""<section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal"><div>
          <span class="eyebrow">Related current affairs</span>
          <h2>Current affairs sets</h2>
          <p>The published quiz sets each issue draws from.</p>
        </div><a class="btn btn-soft" href="subject.html?subject=current-affairs">All current affairs</a></div>
        <div class="grid grid-3">{cards}</div>
      </div>
    </section>""")

    elif coll == "strategy":
        sections.append(subject_strip(index))

    elif coll == "sessions":
        sections.append("""<section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal"><div>
          <span class="eyebrow">How a session runs</span>
          <h2>What every session includes</h2>
          <p>One topic, one slot, one join link - and a written record afterwards.</p>
        </div></div>
        <div class="grid grid-3">
          <div class="card card-pad"><h3>Before</h3><p class="muted">Topic, date,
            time, platform and the join link, published as soon as the slot is
            confirmed.</p></div>
          <div class="card card-pad"><h3>During</h3><p class="muted">One focused
            topic with live questions - bring your doubts and ask them in the
            session.</p></div>
          <div class="card card-pad"><h3>After</h3><p class="muted">A session
            summary, the important questions discussed and the student doubts
            that came up.</p></div>
        </div>
      </div>
    </section>""")

    elif coll == "recruitment":
        sections.append(exam_coverage(exams))
        sections.append("""<section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal"><div>
          <span class="eyebrow">Policy</span>
          <h2>How recruitment information is published</h2>
        </div></div>
        <div class="grid grid-2">
          <div class="card card-pad"><h3>Official sources only</h3>
            <p class="muted">Every record links the recruiting body's own website -
            a government domain - and restates only what that notification says.
            Nothing is copied from jobs aggregators or Telegram forwards.</p></div>
          <div class="card card-pad"><h3>Dates are never guessed</h3>
            <p class="muted">Vacancies, cut-offs and admit cards change between
            notifications, so this portal does not track them. Always read the
            official notification before acting on a date.</p></div>
        </div>
      </div>
    </section>""")

    elif coll == "pdfs":
        sections.append("""<section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal"><div>
          <span class="eyebrow">Offline first</span>
          <h2>Downloads behave like the rest of the site</h2>
          <p>No sign-up, no email wall, no redirect through a third party.</p>
        </div></div>
        <div class="grid grid-3">
          <div class="card card-pad"><h3>One click</h3><p class="muted">Each PDF
            downloads straight from this site's own storage.</p></div>
          <div class="card card-pad"><h3>Tagged</h3><p class="muted">Subject and
            exam tags tell you which paper the sheet belongs to.</p></div>
          <div class="card card-pad"><h3>Free</h3><p class="muted">Everything on
            this portal stays free - study material included.</p></div>
        </div>
      </div>
    </section>""")

    html = head(hub["title"], hub["description"], hub["keywords"], url,
                "website", graph(nodes))
    html += f"""  <main id="main">
    <section class="page-hero">
      <div class="container">
        <nav class="breadcrumb" aria-label="Breadcrumb">
          <a href="index.html">Home</a><span>/</span><span>{esc(hub["schema_hub"])}</span>
        </nav>
        <span class="eyebrow">{esc(hub["eyebrow"])}</span>
        <h1>{esc(hub["h1"])}</h1>
        <p class="muted" style="max-width:70ch">{esc(hub["lead"])}</p>
        <div class="answer-box">
          <span class="ab-label">Quick answer</span>
          <p>{esc(hub["answer"])}</p>
        </div>
      </div>
    </section>
{"".join(sections)}
  </main>
"""
    html += TAIL
    return html, live


def quiz_href(t):
    return (t["landing"].lstrip("/") + ".html") if t.get("landing") else \
        f'quiz.html?subject=current-affairs&topic={t["id"]}'


def subject_strip(index):
    cards = []
    for s in index.get("subjects", []):
        n = sum(1 for c in s.get("categories", []) for t in c.get("topics", [])
                if t.get("available")) + \
            sum(1 for t in s.get("topics", []) if t.get("available"))
        if not n:
            continue
        cards.append(f'<a class="card card-pad reveal" href="subject.html?subject={s["id"]}">'
                     f'<span class="eyebrow">{esc(s.get("icon", ""))} {n} sets</span>'
                     f'<h3>{esc(s.get("name", ""))}</h3>'
                     f'<p class="ilink">Practise now →</p></a>')
    return f"""<section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal"><div>
          <span class="eyebrow">Practice</span>
          <h2>Pair the plan with practice</h2>
          <p>Every subject already has live sets to run the plan against.</p>
        </div><a class="btn btn-soft" href="index.html#subjects">All subjects</a></div>
        <div class="grid grid-3">{"".join(cards)}</div>
      </div>
    </section>"""


def exam_coverage(exams):
    cards = []
    for e in exams:
        slug = e.get("id", "")
        href = f"exam-{slug}.html"
        if not (ROOT / href).exists():
            continue
        rec = next((r for r in RECRUITMENT if r.get("exam") == slug), None)
        badge = ('<span class="badge badge-success">Official link</span>'
                 if rec else '<span class="badge badge-muted">Guide only</span>')
        cards.append(f'<a class="card card-pad reveal" href="{href}">'
                     f'<span class="eyebrow">{badge} Preparation guide</span>'
                     f'<h3>{esc(e.get("name", ""))}</h3>'
                     f'<p class="muted">{esc(e.get("summary", ""))}</p>'
                     f'<p class="ilink">Open guide →</p></a>')
    return f"""<section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal"><div>
          <span class="eyebrow">Posts we cover</span>
          <h2>Every post, with its preparation guide</h2>
          <p>Eligibility, syllabus and selection process for each post live on its
             guide page, written from the official syllabus.</p>
        </div><a class="btn btn-soft" href="punjab-exams.html">All Punjab exams</a></div>
        <div class="grid grid-3">{"".join(cards)}</div>
      </div>
    </section>"""


# =============================================================================
# 8. HOMEPAGE FEED BLOCKS (patched between markers in index.html)
# =============================================================================
FEED_BLOCKS = {
    "notes": "notes",
    "current-affairs": "current-affairs",
    "magazine": "magazine",
    "sessions": "sessions",
    "recruitment": "recruitment",
}


def feed_html(kind, items, index):
    """Static homepage cards for the newest content. Returns '' when a section
    has nothing real to show, so the homepage never advertises empty shelves."""
    if kind == "notes":
        if not items:
            return ""
        cards = "".join(
            f'<a class="card card-pad reveal" href="{r["file"]}">'
            f'<span class="eyebrow">{esc(subject_name(index, r["subjects"][0]) if r["subjects"] else "Study note")}</span>'
            f'<h3>{esc(r["title"])}</h3>'
            f'<p class="muted">{esc(r["description"])}</p>'
            f'<p class="ilink">{r["readingMinutes"]} min read →</p></a>'
            for r in items[:3])
        return cards

    if kind == "current-affairs":
        ca = next((s for s in index.get("subjects", []) if s["id"] == "current-affairs"), None)
        topics = [t for t in (ca.get("topics", []) if ca else []) if t.get("available")]
        topics.sort(key=lambda t: t.get("updatedAt") or 0, reverse=True)
        ca_notes = [r for r in items if "current-affairs" in r["subjects"]]
        cards = "".join(
            f'<a class="card card-pad reveal" href="{quiz_href(t)}">'
            f'<span class="eyebrow">Latest set · {t.get("count", 0)} MCQs</span>'
            f'<h3>{esc(t.get("name", ""))}</h3>'
            f'<p class="ilink">Attempt the set →</p></a>'
            for t in topics[:2])
        cards += "".join(
            f'<a class="card card-pad reveal" href="{r["file"]}">'
            f'<span class="eyebrow">Study note</span>'
            f'<h3>{esc(r["title"])}</h3>'
            f'<p class="ilink">{r["readingMinutes"]} min read →</p></a>'
            for r in ca_notes[:1])
        if not cards:
            return ""
        return f"""    <section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal">
          <div>
            <span class="eyebrow">Latest Current Affairs</span>
            <h2>This month's current affairs</h2>
            <p>Fresh sets and notes - newest first, in Punjabi and English.</p>
          </div>
          <a class="btn btn-soft" href="subject.html?subject=current-affairs">All current affairs</a>
        </div>
        <div class="grid grid-3">{cards}</div>
      </div>
    </section>"""

    if kind == "magazine":
        if not items:
            return ""
        r = items[0]
        return f"""    <section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal">
          <div>
            <span class="eyebrow">Latest Magazine</span>
            <h2>{esc(r["title"])}</h2>
            <p>{esc(r["description"])}</p>
          </div>
          <a class="btn btn-soft" href="magazine.html">Magazine archive</a>
        </div>
        <div class="grid grid-3">
          <a class="card card-pad reveal" href="{r["file"]}">
            <span class="eyebrow">Issue {esc(str(r.get("month", "")))}</span>
            <h3>{esc(r["title"])}</h3>
            <p class="ilink">Read the issue →</p>
          </a>
        </div>
      </div>
    </section>"""

    if kind == "sessions":
        up = [r for r in items if str(r.get("status", "")) == "upcoming"]
        if not up:
            return ""
        r = up[0]
        join = f'<a class="btn btn-primary" href="{esc(str(r.get("join", "")))}" target="_blank" rel="noopener">Join session</a>' \
            if r.get("join") else ""
        return f"""    <section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal">
          <div>
            <span class="eyebrow">Weekly Live Session</span>
            <h2>{esc(r["title"])}</h2>
            <p>{esc(r.get("date", ""))} · {esc(str(r.get("time", "")))} · {esc(str(r.get("platform", "")))}</p>
          </div>
          <a class="btn btn-soft" href="live-sessions.html">All sessions</a>
        </div>
        <div class="btn-row reveal">{join}<a class="btn btn-soft" href="{r["file"]}">Session details →</a></div>
      </div>
    </section>"""

    if kind == "recruitment":
        if not items:
            return ""
        cards = "".join(
            f'<a class="card card-pad reveal" href="{r["file"]}">'
            f'<span class="eyebrow">Official notification</span>'
            f'<h3>{esc(r["title"])}</h3>'
            f'<p class="ilink">Open record →</p></a>' for r in items[:3])
        return f"""    <section class="section" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal">
          <div>
            <span class="eyebrow">Recruitment Updates</span>
            <h2>Official notifications only</h2>
            <p>Links to the recruiting body's own website - never a repost.</p>
          </div>
          <a class="btn btn-soft" href="recruitment.html">All recruitment records</a>
        </div>
        <div class="grid grid-3">{cards}</div>
      </div>
    </section>"""
    return ""


def patch_index(items_by_kind, index):
    path = ROOT / "index.html"
    src = path.read_text(encoding="utf-8")
    out = src
    for kind in FEED_BLOCKS:
        start = f"<!-- HOA-FEED:{kind} -->"
        end = f"<!-- /HOA-FEED:{kind} -->"
        if start not in out or end not in out:
            err(f"index.html: feed marker {start!r} missing - restore it before "
                f"running the content build")
            return
        pre, rest = out.split(start, 1)
        _, post = rest.split(end, 1)
        body = feed_html(kind, items_by_kind.get(kind, []), index)
        out = pre + start + ("\n" + body + "\n" if body else "") + end + post
    if out != src:
        path.write_text(out, encoding="utf-8")
        info("index.html: homepage feed blocks refreshed")


# =============================================================================
# 9. MAIN
# =============================================================================
def main():
    strict = "--strict" in sys.argv
    index = load_index()
    landing = load_quiz_landing()
    exams = []
    try:
        exams = json.loads((ROOT / "data" / "exams.json").read_text(encoding="utf-8")) \
            .get("exams", [])
    except Exception as e:
        err(f"data/exams.json unreadable: {e}")

    # Hub metadata is permanent copy, so it is held to the same contract as
    # every document: a unique title of at most 60 characters and a meta
    # description inside the site's 140-160 character window.
    for _coll, _hub in HUBS.items():
        if len(_hub["title"]) > 60:
            err(f"hub {_coll}: title is {len(_hub['title'])} chars (max 60)")
        if not (140 <= len(_hub["description"]) <= 160):
            err(f"hub {_coll}: description is {len(_hub['description'])} chars "
                f"(want 140-160)")

    global RECRUITMENT
    RECRUITMENT = []

    all_records = {c: [] for c in HUBS}
    punjabi = {c: [] for c in HUBS}

    for coll, cfg in HUBS.items():
        cdir = CONTENT / cfg["dir"]
        if not cdir.exists():
            continue
        for path in sorted(cdir.glob("*.md")):
            if path.name in ("README.md",):
                continue
            name = path.name
            is_pa = name.endswith(".pa.md")
            slug = name[:-6] if is_pa else name[:-3]
            if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", slug):
                err(f"content/{cfg['dir']}/{name}: filename must be lowercase "
                    f"letters, digits and hyphens only")
                continue
            if is_pa:
                if not (cdir / f"{slug}.md").exists():
                    err(f"content/{cfg['dir']}/{name}: Punjabi variant without an "
                        f"English original ({slug}.md)")
                    continue
            rec = build_record(coll, cfg, slug, path, index, "pa" if is_pa else "en")
            if rec is None:
                continue
            (punjabi if is_pa else all_records)[coll].append(rec)

    # Validate EVERYTHING before a single byte is written: a broken file fails
    # the build with nothing half-written on disk.
    if errors:
        for e in errors:
            print(f"  \u274c {e}")
        print(f"\n\u274c content build FAILED with {len(errors)} error(s) - "
              f"no files were written.")
        return 1

    # deterministic order: newest first, then title
    for coll in all_records:
        all_records[coll].sort(key=lambda r: (r["published"], r["title"]), reverse=True)
        punjabi[coll].sort(key=lambda r: (r["published"], r["title"]), reverse=True)

    RECRUITMENT = all_records["recruitment"]

    expected = set()
    manifest_items = []

    # ---- item pages -------------------------------------------------------
    for coll, cfg in HUBS.items():
        if not cfg["prefix"]:
            continue
        pool = all_records[coll]
        for rec in pool + punjabi[coll]:
            html_out, _ = render_item(rec, cfg, pool if rec["lang"] == "en"
                                      else punjabi[coll], index, landing)
            (ROOT / rec["file"]).write_text(html_out, encoding="utf-8")
            expected.add(rec["file"])
            manifest_items.append({k: rec[k] for k in
                                   ("collection", "file", "url", "title",
                                    "description", "published", "updated",
                                    "subjects", "tags", "exams",
                                    "readingMinutes", "lang")
                                   if k in rec} | {
                "path": rec["path"],
                **({"month": str(rec["month"])} if rec.get("month") else {}),
                **({"date": str(rec["date"])} if rec.get("date") else {}),
                **({"status": str(rec["status"])} if rec.get("status") else {}),
                **({"post": str(rec["post"])} if rec.get("post") else {}),
                **({"official_url": str(rec["official_url"])} if rec.get("official_url") else {}),
                **({"pdf": str(rec["pdf"])} if rec.get("pdf") else {}),
            })
        info(f"{coll}: {len(pool)} english + {len(punjabi[coll])} punjabi page(s)")

    # ---- hubs -------------------------------------------------------------
    hubs_out = []
    for coll, cfg in HUBS.items():
        pool = all_records[coll] + punjabi[coll]
        html_out, live = hub_page(coll, cfg, pool, index, exams)
        (ROOT / cfg["file"]).write_text(html_out, encoding="utf-8")
        expected.add(cfg["file"])
        hubs_out.append({
            "collection": coll,
            "file": cfg["file"],
            "url": f'{DOMAIN}/{cfg["file"][:-5]}',
            "title": HUBS[coll]["title"],
            "description": HUBS[coll]["description"],
            "count": len(live),
        })
        info(f"hub {cfg['file']}: {len(live)} item(s)")

    # ---- pdf registry -----------------------------------------------------
    pdf_url = f'{DOMAIN}/{HUBS["pdfs"]["file"][:-5]}'
    pdfs = [{
        "title": r["title"],
        "description": r["description"],
        "path": str(r["meta"].get("file", "")),
        "subjects": r["subjects"],
        "exams": r["exams"],
        "lang": r["lang"],
        "url": pdf_url,
    } for r in all_records["pdfs"] + punjabi["pdfs"]]

    # ---- stale output removal --------------------------------------------
    removed = []
    for fn in sorted(os.listdir(ROOT)):
        if fn.endswith(".html") and fn.startswith(GEN_PREFIXES) and fn not in expected:
            (ROOT / fn).unlink()
            removed.append(fn)
    if removed:
        warn("stale content pages removed: " + ", ".join(removed))

    # ---- homepage feed ----------------------------------------------------
    feed_items = {
        "notes": all_records["notes"] + punjabi["notes"],
        "current-affairs": all_records["notes"] + punjabi["notes"],
        "magazine": all_records["magazine"] + punjabi["magazine"],
        "sessions": all_records["sessions"] + punjabi["sessions"],
        "recruitment": all_records["recruitment"] + punjabi["recruitment"],
    }
    patch_index(feed_items, index)

    # ---- manifest ---------------------------------------------------------
    manifest = {
        "version": 1,
        "domain": DOMAIN,
        "hubs": hubs_out,
        "items": sorted(manifest_items, key=lambda r: r["file"]),
        "pdfs": pdfs,
        "counts": {c: len(all_records[c]) + len(punjabi[c]) for c in HUBS},
        "generatedBy": "scripts/build_content.py",
    }
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
                        encoding="utf-8")
    info(f"manifest: {len(hubs_out)} hubs, {len(manifest_items)} item page(s), "
         f"{len(pdfs)} pdf record(s) -> data/content-manifest.json")

    # ---- report -----------------------------------------------------------
    for w in warnings:
        print(f"  \u26a0 {w}")
    for n in notes:
        print(f"  \u2139 {n}")
    if errors:
        print()
        for e in errors:
            print(f"  \u274c {e}")
        print(f"\n\u274c content build FAILED with {len(errors)} error(s).")
        return 1
    if strict and warnings:
        print(f"\n\u274c content build FAILED (--strict): {len(warnings)} warning(s).")
        return 1
    print("\n\u2705 Content build complete.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
