#!/usr/bin/env bash
# ci.sh — the Phase 0 gate. Run it locally (`bash scripts/ci.sh`) and in CI.
#
#   1. rebuild the manifest with both builders (byte-parity when Node exists)
#   2. rebuild the SEO landing set
#   3. run scripts/seo_check.py
#   4. run scripts/rich_results_check.py
#   5. prove the committed tree is exactly what those builders emit
#
# Step 5 is what makes "the gates passed" meaningful: a green seo_check on a
# stale checkout proves nothing. Only the four files that legitimately carry a
# run timestamp are normalised back to their committed value first, so a real
# content drift still fails the diff.
#
# Exit code 0 = every gate passed and the working tree matches the builders.
set -euo pipefail
cd "$(dirname "$0")/.."

step() { printf '\n\033[1m· %s\033[0m\n' "$1"; }

step "1/5 manifest — python3 scripts/build_index.py"
python3 scripts/build_index.py

if command -v node >/dev/null 2>&1; then
  step "2/5 manifest parity — node scripts/build-index.mjs"
  cp data/index.json /tmp/hoa-index.py.json
  cp sitemap.xml /tmp/hoa-sitemap.py.xml
  node scripts/build-index.mjs
  # volatile fields (generatedAt, lastmod) are allowed to differ between runs
  norm() { grep -v -e '"generatedAt"' -e '<lastmod>' || true; }
  if ! diff -u <(norm < /tmp/hoa-index.py.json) <(norm < data/index.json); then
    echo "FAIL: build_index.py and build-index.mjs disagree on data/index.json" >&2
    exit 1
  fi
  if ! diff -u <(norm < /tmp/hoa-sitemap.py.xml) <(norm < sitemap.xml); then
    echo "FAIL: build_index.py and build-index.mjs disagree on sitemap.xml" >&2
    exit 1
  fi
  echo "  parity OK (both builders emit the same bytes)"
else
  step "2/5 manifest parity — skipped (node not installed; CI runs it)"
fi

step "3/5 landing pages — python3 scripts/build_landing_pages.py"
python3 scripts/build_landing_pages.py

step "4/5 gates"
python3 scripts/seo_check.py
python3 scripts/rich_results_check.py

step "5/5 committed tree matches the builders"
python3 - <<'PY'
"""Rewrite the four run-timestamped fields to their committed values."""
import re
import subprocess
from pathlib import Path

# file -> (regex, replace_all). The committed match is authoritative: the
# builders stamp "now" into these fields, so a run on another day must not
# look like content drift.
VOLATILE = {
    "data/index.json": [(r'"generatedAt": "[^"]*"', False)],
    "data/landing-manifest.json": [(r'"generatedAt": "[^"]*"', False)],
    "SEO-LANDING-REPORT.md": [(r"Generated by `scripts/build_landing_pages\.py` on [^.]*\.", False)],
    "sitemap.xml": [(r"<lastmod>[^<]*</lastmod>", True)],   # one per URL
}
for path, patterns in VOLATILE.items():
    head = subprocess.run(["git", "show", f"HEAD:{path}"], capture_output=True,
                          text=True, check=True).stdout
    p = Path(path)
    work = p.read_text(encoding="utf-8")
    changed = False
    for pat, replace_all in patterns:
        m = re.search(pat, head)
        if not m:
            continue
        repl = m.group(0).replace("\\", "\\\\")
        work, n = re.subn(pat, repl, work,
                          count=0 if replace_all else 1)
        changed = changed or n > 0
    if changed:
        p.write_text(work, encoding="utf-8")
        print(f"  normalised timestamps in {path}")
PY

if ! git diff --exit-code; then
  echo "FAIL: the committed tree does not match what the builders emit." >&2
  echo "      Commit the regenerated files (or fix the builder)." >&2
  exit 1
fi
echo "  committed tree matches the builders"
echo
echo "ALL GATES GREEN"
